var countries = {
'RW': 'Rwanda',
'SO': 'Somalia',
'YE': 'Jemen',
'IQ': 'Irak',
'SA': 'Arabia Saudyjska',
'IR': 'Iran',
'CY': 'Cypr',
'TZ': 'Tanzania',
'SY': 'Syria',
'AM': 'Armenia',
'KE': 'Kenia',
'CD': 'Kongo',
'DJ': 'Dżibuti',
'UG': 'Uganda',
'CF': 'Republika Afryki Środkowej',
'SC': 'Seszele',
'JO': 'Królestwo Jordanii',
'LB': 'Liban',
'KW': 'Kuwejt',
'OM': 'Oman',
'QA': 'Katar',
'BH': 'Bahrajn',
'AE': 'Zjednoczone Emiraty Arabskie',
'IL': 'Izrael',
'TR': 'Turcja',
'ET': 'Etiopia',
'ER': 'Erytrea',
'EG': 'Egipt',
'SD': 'Sudan',
'GR': 'Grecja',
'BI': 'Burundi',
'EE': 'Estonia',
'LV': 'Łotwa',
'AZ': 'Azerbejdżan',
'LT': 'Litwa',
'SJ': 'Svalbard i Jan Mayen',
'GE': 'Gruzja',
'MD': 'Mołdawia',
'BY': 'Białoruś',
'FI': 'Finlandia',
'AX': 'Åland',
'UA': 'Ukraina',
'MK': 'Macedonia',
'HU': 'Węgry',
'BG': 'Bułgaria',
'AL': 'Albania',
'PL': 'Polska',
'RO': 'Rumunia',
'XK': 'Kosowo',
'ZW': 'Zimbabwe',
'ZM': 'Zambia',
'KM': 'Komory',
'MW': 'Malawi',
'LS': 'Lesoto',
'BW': 'Botswana',
'MU': 'Mauritius',
'SZ': 'Swazi',
'RE': 'Réunion',
'ZA': 'Afryka Południowa',
'YT': 'Mayotte',
'MZ': 'Mozambik',
'MG': 'Madagaskar',
'AF': 'Afganistan',
'PK': 'Pakistan',
'BD': 'Bangladesz',
'TM': 'Turkmenistan',
'TJ': 'Tadżykistan',
'LK': 'Sri Lanka',
'BT': 'Bhutan',
'IN': 'Indie',
'MV': 'Malediwy',
'IO': 'Brytyjskie Terytoria Oceanu Indyjskiego',
'NP': 'Nepal',
'MM': 'Myanmar [Birma]',
'UZ': 'Uzbekistan',
'KZ': 'Kazachstan',
'KG': 'Kirgistan',
'TF': 'Terytoria Francji Południowej',
'HM': 'Heard Island and McDonald Islands',
'CC': 'Cocos [Keeling] Islands',
'PW': 'Palau',
'VN': 'Wietnam',
'TH': 'Tajlandia',
'ID': 'Indonezja',
'LA': 'Laos',
'TW': 'Tajwan',
'PH': 'Filipiny',
'MY': 'Malezja',
'CN': 'Chiny',
'HK': 'Hong Kong',
'BN': 'Brunei',
'MO': 'Makao',
'KH': 'Kambodża',
'KR': 'Korea Południowa',
'JP': 'Japonia',
'KP': 'Korea Północna',
'SG': 'Singapur',
'CK': 'Wyspy Cooka',
'TL': 'Timor Wschodni',
'RU': 'Federacja Rosyjska',
'MN': 'Mongolia',
'AU': 'Australia',
'CX': 'Wyspa Bożego Narodzenia',
'MH': 'Wyspy Marshalla',
'FM': 'Mikronezja',
'PG': 'Papua Nowa Gwinea',
'SB': 'Wyspy Solomona',
'TV': 'Tuvalu',
'NR': 'Nauru',
'VU': 'Vanuatu',
'NC': 'Nowa Kaledonia',
'NF': 'Norfolk Island',
'NZ': 'Nowa Zelandia',
'FJ': 'Fidżi',
'LY': 'Libia',
'CM': 'Kamerun',
'SN': 'Senegal',
'CG': 'Kongo',
'PT': 'Portugalia',
'LR': 'Liberia',
'CI': 'Wybrzeże Kości Słoniowej',
'GH': 'Ghana',
'GQ': 'Gwinea Równikowa',
'NG': 'Nigeria',
'BF': 'Burkina Faso',
'TG': 'Togo',
'GW': 'Guinea-Bissau',
'MR': 'Mauretania',
'BJ': 'Benin',
'GA': 'Gabon',
'SL': 'Sierra Leone',
'ST': 'São Tomé and Príncipe',
'GI': 'Gibraltar',
'GM': 'Gambia',
'GN': 'Gwinea',
'TD': 'Czad',
'NE': 'Niger',
'ML': 'Mali',
'EH': 'Sahara Zachodnia',
'TN': 'Tunezja',
'ES': 'Hiszpania',
'MA': 'Marokp',
'MT': 'Malta',
'DZ': 'Algieria',
'FO': 'Wyspy Owcze',
'DK': 'Dania',
'IS': 'Islandia',
'GB': 'Zjednoczone Królestwo Brytyjskie',
'CH': 'Szwajcaria',
'SE': 'Szwecja',
'NL': 'Holandia',
'AT': 'Austria',
'BE': 'Belgia',
'DE': 'Niemcy',
'LU': 'Luksemburg',
'IE': 'Irlandia',
'MC': 'Monako',
'FR': 'Francja',
'AD': 'Andora',
'LI': 'Liechtenstein',
'JE': 'Jersey',
'IM': 'Isle of Man',
'GG': 'Guernsey',
'SK': 'Słowacja',
'CZ': 'Czechy',
'NO': 'Norwegia',
'VA': 'Watykan',
'SM': 'San Marino',
'IT': 'Włochy',
'SI': 'Słowenia',
'ME': 'Czarnogóra',
'HR': 'Chorwacja',
'BA': 'Bośnia i Hercegowina',
'AO': 'Angola',
'NA': 'Namibia',
'SH': 'Saint Helena',
'BB': 'Barbados',
'CV': 'Cabo Verde',
'GY': 'Gujana',
'GF': 'Gujana Francuska',
'SR': 'Surinam',
'PM': 'Saint Pierre and Miquelon',
'GL': 'Grenlandia',
'PY': 'Paragwaj',
'UY': 'Urugwaj',
'BR': 'Brazylia',
'FK': 'Falklandy',
'GS': 'South Georgia and the South Sandwich Islands',
'JM': 'Jamajka',
'DO': 'Dominikana',
'CU': 'Kuba',
'MQ': 'Martynika',
'BS': 'Bahamy',
'BM': 'Bermudy',
'AI': 'Anguilla',
'TT': 'Trinidad i Tobago',
'KN': 'St Kitts and Nevis',
'DM': 'Dominika',
'AG': 'Antigua and Barbuda',
'LC': 'Saint Lucia',
'TC': 'Turks and Caicos Islands',
'AW': 'Aruba',
'VG': 'British Virgin Islands',
'VC': 'Saint Vincent and the Grenadines',
'MS': 'Montserrat',
'MF': 'Saint Martin',
'BL': 'Saint-Barthélemy',
'GP': 'Gwadelupa',
'GD': 'Grenada',
'KY': 'Cayman Islands',
'BZ': 'Belize',
'SV': 'El Salvador',
'GT': 'Gwatemala',
'HN': 'Honduras',
'NI': 'Nikaragua',
'CR': 'Kostaryka',
'VE': 'Wenezuela',
'EC': 'Ekwador',
'CO': 'Kolumbia',
'PA': 'Panama',
'HT': 'Haiti',
'AR': 'Argentyna',
'CL': 'Chile',
'BO': 'Boliwia',
'PE': 'Peru',
'MX': 'Meksyk',
'PF': 'Polinezja Francuska',
'PN': 'Pitcairn Islands',
'KI': 'Kiribati',
'TK': 'Tokelau',
'TO': 'Tonga',
'WF': 'Wallis and Futuna',
'WS': 'Samoa',
'NU': 'Niue',
'MP': 'Northern Mariana Islands',
'GU': 'Guam',
'PR': 'Puerto Rico',
'VI': 'U.S. Virgin Islands',
'UM': 'U.S. Minor Outlying Islands',
'AS': 'American Samoa',
'CA': 'Kanada',
'US': 'Stany Zjednoczone',
'PS': 'Palestyna',
'RS': 'Serbia',
'AQ': 'Antarktyka',
'SX': 'Sint Maarten',
'CW': 'Curaçao',
'BQ': 'Bonaire, Sint Eustatius, and Saba',
'SS': 'Sudan Południowy',
};

var geoip = {
	'getName': function(code){
		var name = countries[code];
		if(name == undefined) return false;
		return name;
	}
};
