var lang = {
	'pl': {
		'messagePatterns': {
			'nickChange': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> <span class="modeinfo">%s</span> zmienił nick na <span class="modeinfo">%s</span></span></div>',
			'nickInUse': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick"><span class="symbolFont">✯</span> <span class="modeinfo">%s</span>: Nick jest już używany przez kogoś innego.</span></div>',
			'badNick': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick"><span class="symbolFont">⮿</span> <span class="modeinfo">%s</span>: Nick nie jest dostępny.</span></div>',
			'nickChangeOwn': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Jesteś teraz znany jako <span class="modeinfo">%s</span></span></div>',
			'joinOwn': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="join"><span class="symbolFont">🢡</span> Dołączyłeś <i class="userhost">(%s!%s@%s)</i> do kanału <span class="modeinfo">%s</span>.</span></div>',
			'join': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="join"><span class="symbolFont">🢡</span> <b>%s</b> <i class="userhost">[%s@%s]</i> dołączył do <span class="modeinfo">%s</span>.</span></div>',
			'part': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="part"><span class="symbolFont">🢠</span> <b>%s</b> <i class="userhost">[%s@%s]</i> opuścił <span class="modeinfo">%s</span> [%s]</span></div>',
			'quit': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="part"><span class="symbolFont">🢠</span> <b>%s</b> <i class="userhost">[%s@%s]</i> opuścił IRC [%s]</span></div>',
			'partOwn': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="part"><span class="symbolFont">🢠</span> Opuściłeś kanał <span class="modeinfo">%s</span>. <a href="#" onclick="gateway.send(\'JOIN %s\')">Dołącz ponownie</a></span></div>',
			'channelMsg': '<div class="messageDiv %s" %s><div class="messageMeta">%s</div><div class="messageHeader"><span class="time">%s &nbsp;</span><span class="nick">&lt;<span %s>%s</span>&gt;%s</span></div><span class="msgText">%s</span></div>',
			'yourMsg': '<div class="messageDiv %s" %s><div class="messageMeta">%s</div><div class="messageHeader"><span class="time">%s &nbsp;</span><span class="yournick">&lt;<span %s>%s</span>&gt;%s</span></div><span class="msgText">%s</span></div>',
			'channelMsgHilight': '<div class="messageDiv %s" %s><div class="messageMeta">%s</div><div class="messageHeader"><span class="time">%s &nbsp;</span><span class="hilight"><span class="nick">&lt;%s&gt;%s</span></span></div><span class="msgText">%s</span></div>',
			'channelAction': '<div class="messageDiv %s" %s><span class="time">%s</span> &nbsp; <span class="symbolFont">❇</span> <span class="nick"><span %s>%s</span></span> %s</div>',
			'yourAction': '<div class="messageDiv %s" %s><span class="time">%s</span> &nbsp; <span class="symbolFont">❇</span> <span class="yournick"><span %s>%s</span></span> %s</div>',
			'channelActionHilight': '<div class="messageDiv %s" %s><span class="time">%s</span> &nbsp; <span class="symbolFont">❇</span> <span class="hilight"><span class="nick">%s</span> %s</span></div>',
			'changeTopic': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> <span class="modeinfo">%s</span> zmienił temat na: %s</span></div>',
			'deleteTopic': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> <span class="modeinfo">%s</span> usunął temat <span class="modeinfo">%s</span></span></div>',
			'topic': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Temat kanału <span class="modeinfo">%s</span>: %s</span></div>',
			'topicNotSet': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Temat <span class="modeinfo">%s</span> nie jest ustawiony</span></div>',
			'topicTime': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Temat ustawiony przez <span class="modeinfo">%s</span> [%s]</span></div>',
			'kick': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick"><span class="symbolFont">✀</span> <span class="modeinfo">%s</span> wyrzucił <span class="modeinfo">%s</span> z <span class="modeinfo">%s</span> [Powód: %s]</span></div>',
			'kickOwn': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick"><span class="symbolFont">✀</span> <span class="modeinfo">%s</span> wyrzucił cię z <span class="modeinfo">%s</span> [Powód: %s]</span></div>',
			'modeChange': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">🔧</span> <span class="modeinfo">%s</span> %s na kanale <span class="modeinfo">%s</span></span></div>',
			'mode': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">🔧</span> Ustawienia kanału <span class="modeinfo">%s</span>: %s</span></div>',
			'umode': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">🔧</span> Ustawienia nicka <span class="modeinfo">%s</span>: %s</span></div>',
			'creationTime': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Kanał stworzony: %s</span></div>',
			'startedQuery': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="join"><span class="symbolFont">🢡</span> Rozpoczęto rozmowę z <span class="modeinfo">%s</span>. <a onclick="ignore.askIgnore(\'%s\');">Ignoruj tego użytkownika</a> / <a onclick="disp.showQueryUmodes()">Blokowanie wiadomości prywatnych</a></span></div>',
			'queryBacklog': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="join"><span class="symbolFont">✯</span> Zapis poprzedniej rozmowy z <span class="modeinfo">%s</span>:</span></div>',
			'channelBacklog': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Zapis poprzedniej wizyty na <span class="modeinfo">%s</span>:</span></div>',
			'channelBacklogEnd': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Koniec zapisu.</span></div>',
			'noSuchCommand': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">⮿</span> <span class="modeinfo">%s</span>: nieznana komenda.</span></div>',
			'noSuchNick': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">⮿</span> <span class="modeinfo">%s</span>: nie ma takiego nicku ani kanału</span></div>',
			'noSuchNickHistory': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">⮿</span> <span class="modeinfo">%s</span>: brak historii wizyt nicka</span></div>',
			'noSuchChannel': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">⮿</span> <span class="modeinfo">%s</span>: nie ma takiego kanału</span></div>',
			'notOnChannel': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">⮿</span> <span class="modeinfo">%s</span>: nie jesteś na tym kanale</span></div>',
			'alreadyOnChannel': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">⮿</span> %s: <span class="modeinfo">%s</span> jest już na tym kanale</span></div>',
			'youQuit': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="part"><span class="symbolFont">✯</span> Wyszedłeś z IRC</span></div>',
			'notConnected': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">⮿</span> Nie jesteś połączony z IRC!</span></div>',
			'notEnoughParameters': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">⮿</span> <span class="modeinfo">%s</span>: Za mało argumentów.</span></div>',
			'cannotSendToChan': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick"><span class="symbolFont">⮿</span> Nie można wysłać na <span class="modeinfo">%s</span>: %s. Wiadomość nie została dostarczona.</span></div>',
			'cannotSendToUser': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick"><span class="symbolFont">⮿</span> Nie można pisać do <span class="modeinfo">%s</span>: %s. Wiadomość nie została dostarczona.</span></div>',
			'cannotJoin': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick"><span class="symbolFont">⮿</span> Nie można dołączyć do kanału <span class="modeinfo">%s</span>: %s</span></div>',
			'noPerms': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick"><span class="symbolFont">⮿</span> Brak uprawnień.</span></div>',
			'notice': '<div class="messageDiv %s" %s><span class="time">%s</span> &nbsp; <span class="notice-nick"><b>-%s-</b></span><span class="userhost">(<span class="notice-nick">%s</span>@<span class="notice-nick">%s</span>)</span> <span class="notice">%s</span></div>',
			'serverNotice': '<div class="messageDiv" %s><span class="time">%s</span> &nbsp; <span class="notice-nick">Wiadomość od serwera <b>%s</b>:</span> <span class="notice">%s</span></div>',
			'yourNotice': '<div class="messageDiv %s" %s><span class="time">%s</span> &nbsp; <span class="notice"><b>-NOTICE/%s-</b> %s</span></div>',
			'yourServiceCommand': '<div class="messageDiv %s" %s><span class="time">%s</span> &nbsp; <span class="notice"><b>[%s → %s]</b> %s</span></div>',
			'notEnoughParams': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">⮿</span> <span class="modeinfo">%s</span>: za mało argumentów: %s</span></div>',
			'motd': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="motd"><span class="symbolFont">✯</span> %s</span></div>',
			'SaslAuthenticate': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="sinfo"><span class="symbolFont">🔧</span> %s</span></div>',
			'ctcpRequest': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> <span class="modeinfo">%s</span> wysyła CTCP REQUEST: %s</span></div>',
			'ctcpReply': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="notice"><span class="symbolFont">✯</span> <b>CTCP REPLY od %s:</b> %s</span></div>',
			'chanListElement': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="notice"><span class="symbolFont">✯</span> <b><a href="#" onClick="gateway.send(\'JOIN %s\')">%s</a></b> (%s) - %s </span> </div>',
			'chanListElementHidden': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="notice"><span class="symbolFont">✯</span> <b>(kanał ukryty)</b> (%s) - (temat ukryty) </span> </div>',
			'error': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"> <span class="symbolFont">⮿</span> Rozłączono z serwerem: %s</span></div>',
			'existingConnection': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Połączenie już istnieje, dołączam się do niego.</span></div>',
			'away': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">🍵</span> <span class="modeinfo">%s</span> otrzymał twoją wiadomość, ale jest teraz nieobecny: %s</span></div>',
			'yourAwayEnabled': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">🍵</span> Jesteś teraz oznaczony jako nieobecny</span></div>',
			'yourAwayDisabled': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">🍵</span> Nie jesteś już oznaczony jako nieobecny</span></div>',
			'yourInvite': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Zaprosiłeś użytkownika <span class="modeinfo">%s</span> na kanał <span class="modeinfo">%s</span></span></div>',
			'knocked': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Poprosiłeś o dostęp ("zapukałeś") na <span class="modeinfo">%s</span>, czekaj na zaproszenie od operatora. Pamiętaj, że w danej chwili żaden operator może nie być przy komputerze. W takiej sytuacji zaczekaj kilkadziesiąt minut i spróbuj jeszcze raz.</span></div>',
			'listShown': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Lista kanałów będzie wyświetlona w zakładce statusu.</span></div>',
			'channelIgnoreAdded': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Dodano <b>%s</b> do ignorowanych na kanałach.</span></div>',
			'channelIgnoreRemoved': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Usunięto <b>%s</b> z ignorowanych na kanałach.</span></div>',
			'queryIgnoreAdded': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Dodano <b>%s</b> do ignorowanych prywatnie.</span></div>',
			'queryIgnoreRemoved': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Usunięto <b>%s</b> z ignorowanych prywatnie.</span></div>',
			'ignoreListStart': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Lista ignorowanych:</span></div>',
			'ignoreListEnd': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Koniec listy.</span></div>',
			'ignoreListEmpty': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Lista ignorowanych jest pusta.</span></div>',
			'ignoreListItem': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Typ: <b>%s</b>, maska: <b>%s</b></span></div>',
			'netsplit': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="part"><span class="symbolFont">🢠</span> <span class="netsplit">Netsplit</span>, wychodzą: %s</span></div>',
			'netjoin': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="join"><span class="symbolFont">🢡</span> Po <span class="netjoin">netsplicie</span> wchodzą: %s</span></div>',
			'displayedHost': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="sinfo"><span class="symbolFont">🔧</span> Twój host jest teraz widoczny jako %s</span></div>',
			'invalidMode': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick"><span class="symbolFont">⮿</span> Nieprawidłowy tryb "%s"</span></div>',
			'unimplemented': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="sinfo"><span class="symbolFont">✯</span> %s</span></div>',
			'unimplementedError': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick"><span class="symbolFont">⮿</span> %s</span></div>'
		},
		'SASLLogin': 'SASL: logowanie do konta ',
		'SASLLoginAttempt': 'Próba logowania za pomocą SASL...',
		'recoverErrorHtml': '<h2>Błąd ogólny</h2><p>Inna sesja rozłączyła Cię używając polecenia RECOVER. Może masz otwartą więcej niż jedną bramkę?</p>',
		'error': 'Błąd',
		'serverClosedConnection': 'Serwer przerwał połączenie',
		'informations': 'Informacje',
		'inviting': 'zaprasza Cię na kanał',
		'enter': 'Wejdź',
		'ignore': 'Zignoruj',
		'invitation': 'Zaproszenie',
		'userSoftware': 'Oprogramowanie użytkownika ',
		'networkServiceMessage': 'Komunikat od usługi sieciowej',
		'privateNoticeFrom': 'Komunikat prywatny od ',
		'privateNoticeFromServer': 'Komunikat prywatny od serwera ',
		'realNickname': 'Prawdziwy nick na IRC',
		'notLoggedIn': 'Niezalogowany',
		'loggedIn': 'Zalogowany',
		'loggedInAs': 'Zalogowany jako ',
		'warning': 'Ostrzeżenie',
		'yourCurrentNickIs': 'Twój bieżący nick to ',
		'notPresent': 'Nieobecny',
		'isNotPresent': ' jest nieobecny(a): ',
		'nickRegistered': 'Ten nick jest zarejestrowany',
		'fullMask': 'Pełna maska',
		'realname': 'Realname',
		'userInformation': 'Informacje o użytkowniku ',
		'server': 'Serwer',
		'seen': 'Widziano',
		'ircop': 'OPERATOR SIECI',
		'networkService': 'Usługa sieciowa',
		'previousVisitsBy': 'Poprzednie wizyty ',
		'signedOn': 'Połączył się',
		'idle': 'Nieaktywny',
		'hoursShort': 'h',
		'minutesShort': 'min',
		'secondsShort': 'sek',
		'joinChannel': 'Dołącz do kanału',
		'channels': 'Kanały',
		'isConnectingFrom': 'Łączy się z: ',
		'noTopic': 'brak tematu',
		'fullList': 'Pełna lista',
		'refresh': 'Odśwież',
		'largestChannels': 'Największe kanały',
		'accountName': 'Nazwa konta',
		'isBotHtml': 'Ten użytkownik to <b>bot</b>',
		'nickListFor': 'Lista nicków dla ',
		'noSuchNickChannel': 'Nie można wykonać żądanej akcji. Nie ma takiego nicku ani kanału',
		'noSuchObject': 'Nie można wykonać żądanej akcji. Nie ma takiego obiektu',
		'noSuchChannel': 'Nie można wykonać żądanej akcji. Nie ma takiego kanału',
		'needVoice': 'Potrzebujesz prawa głosu, aby teraz pisać na tym kanale',
		'youreBanned': 'Jesteś zbanowany',
		'colorsForbidden': 'Wiadomości zawierające kolory są zabronione na tym kanale',
		'noExternalMsgs': 'Musisz być na tym kanale, aby móc pisać',
		'registeredNickRequired': 'Musisz mieć zarejestrowanego nicka, aby teraz pisać na tym kanale',
		'serverMessageIs': 'Komunikat od serwera: ',
		'cantSendMessageTo': 'Nie można wysłać wiadomości do ',
		'recentVisitsForNickNotFound': 'Nie znaleziono poprzednich wizyt nicka: ',
		'isCurrentlyNotAvailable': ' jest niedostępny. Spróbuj poczekać kilka minut.',
		'nickname': 'Nick',
		'yourCurrentNickIs': 'Twój bieżący nick to ',
		'isAlreadyUsedBySomeone': ' jest już używany przez kogoś innego.',
		'youreNotOnChannel': ' nie jesteś na tym kanale.',
		'isAlreadyOnChannel': ' jest już na tym kanale.',
		'cantChangeNickMessageHtml': 'Nie można zmienić nicka.<br>Komunikat od serwera: ',
		'invalidMode': 'Nieprawidłowy tryb',
		'cantJoin': 'Nie można dołączyć do kanału',
		'inviteRequired': 'Musisz dostać zaproszenie aby wejść na ten kanał.',
		'inviteRequiredShort': 'Kanał wymaga zaproszenia',
		'askOpersForEntry': 'Poproś operatorów o możliwość wejścia',
		'entryRequest': 'Proszę o możliwość wejścia na kanał',
		'needValidPassword': 'Musisz podać poprawne hasło',
		'passwordRequired': 'Wymagane hasło',
		'registerYourNickToJoin': 'Kanał wymaga, aby Twój nick był zarejestrowany. Zastosuj się do instrukcji otrzymanych od NickServ.',
		'registeredNickRequiredForChan': 'Kanał wymaga zarejestrowanego nicka',
		'cantKnock': 'Nie można zapukać do kanału.',
		'noAccess': 'brak uprawnień',
		'notEnoughPrivileges': 'Nie masz wystarczających uprawnień aby wykonać żądaną akcję.',
		'cantSendPMTo': 'Nie można wysłać prywatnej wiadomości do ',
		'cantSendPM': 'Nie można wysłać prywatnej wiadomości.',
		'yourNickMustBeRegistered': 'Twój nick musi być zarejestrowany',
		'userAcceptsPMsOnlyFromRegistered': 'Użytkownik akceptuje prywatne wiadomości tylko od zarejestrowanych nicków.',
		'SSLRequired': 'Kanał wymaga połączenia z włączonym SSL.',
		'noPermsForAction': 'Nie masz wystarczających uprawnień aby wykonać żądaną akcję',
		'hasSecureConnection': 'Używa bezpiecznego połączenia',
		'weAreLoggedInAs': 'Zalogowano jako ',
		'SASLLoginSuccess': 'SASL: logowanie udane.',
		'SASLLoginFail': 'SASL: logowanie nieudane!',
		'suppliedNickPassword': 'Podane hasło do nicka ',
		'passwordInvalidTryAgain': ' jest błędne. Możesz spróbować ponownie lub zmienić nicka.',
		'SASLNotLoggedIn': 'SASL: nie zalogowano.',
		'gatewayVersionIs': 'Bramka WWW PIRC.PL, wersja ',
		'versionWithAddons': ', z dodatkami: ',
		'runningOn': 'na',
		'unknown': 'Nieznany',
		'chStatusInfo': [ 'Niezarejestrowany', 'Prawo głosu', 'Pół-operator', 'Operator', 'Admin', 'Właściciel', 'Zarejestrowany' ],
		'modes': {
			/* unrealircd mode comments */
			'changeableSingle': [
				['m', 'Kanał moderowany'],
				['i', 'Tylko na zaproszenie'],
				['s', 'Kanał ukryty'],
				['R', 'Tylko dla zarejestrowanych nicków'],
				['N', 'Zakaz zmiany nicków'],
				['Q', 'Zakaz kopania'],
				['M', 'Do mówienia wymagany zarejestrowany nick lub co najmniej +v'],
				['t', 'Tylko operator może zmieniać temat'],
				['n', 'Nie można wysyłać wiadomości nie będąc na kanale'],
				['D', 'Użytkownicy będą widoczni na liście tylko wtedy, gdy coś napiszą']
			],
			'changeableArg': [
				['k', 'Hasło do kanału'],
				['l', 'Maksymalna ilość użytkowników']
			],
			'chModeInfo': {
				'q': 'status właściciela',
				'a': 'status admina',
				'o': 'status operatora',
				'h': 'status pół-operatora',
				'v': 'prawo głosu',
				'k': 'hasło:',
				'b': 'bana na',
				'e': 'wyjątek bana na',
				'I': 'stałe zaproszenie na',
				'f': 'zabezpieczenie przed floodem:',
				'p': 'tryb prywatny',
				's': 'tryb ukryty',
				'm': ['moderację', 'kanał moderowany'],
				'n': 'brak wiadomości z zewnątrz',
				't': ['ochronę tematu', 'chroniony temat'],
				'i': 'wejście tylko na zaproszenie',
				'r': ['rejestrację', 'zarejestrowany'],
				'R': 'wejście tylko dla zarejestrowanych',
				'c': ['blokadę kolorów', 'blokada kolorów'],
				'O': 'tryb O',
				'Q': ['blokadę kopania', 'zablokowane kopanie'],
				'K': ['blokadę pukania', 'zablokowane pukanie'],
				'V': ['blokadę zaproszeń', 'zablokowane zaproszenia'],
				'C': ['blokadę CTCP', 'zablokowane CTCP'],
				'z': 'wejście tylko dla połączeń szyfrowanych',
				'N': ['blokadę zmian nicków', 'zablokowana zmiana nicków'],
				'S': 'usuwanie kolorów',
				'M': ['moderację niezarejestrowanych', 'niezarejestrowani są moderowani'],
				'T': ['blokadę NOTICE', 'zablokowane NOTICE'],
				'G': 'tryb G',
				'D': 'tryb D: użytkownicy będą widoczni na liście tylko wtedy, gdy coś napiszą',
				'd': 'tryb d',
				'L-add': 'przekierowanie na kanał',
				'L-remove': 'przekierowanie na inny kanał',
				'l-add': 'limit użytkowników na',
				'l-remove': 'limit użytkowników',
				'H-add': 'pamięć historii kanału',
				'H-remove': 'pamięć historii kanału'
			},
			'chStatusNames': {
				'q': 'owner',
				'a': 'admin',
				'o': 'op',
				'h': 'halfop',
				'v': 'voice'
			},
		},
		'newMessage': 'Nowa wiadomość',
		'loading': 'Ładowanie',
		'loadingWait': 'Poczekaj, trwa ładowanie...',
		'outdatedBrowser': 'Przestarzała przeglądarka',
		'': 'Twoja przeglądarka jest przestarzała i nie jest obsługiwana. Należy zaktualizować przeglądarkę Internet Explorer do wersji 9 lub wyższej albo użyć innej przeglądarki (Firefox, Opera, Chrome, Safari) w którejś z nowszych wersji.<br />Jeżeli posiadasz przeglądarkę Internet Explorer w wersji 9 lub wyższej i widzisz ten komunikat wyłącz tzw "widok zgodności" dla tej strony.',
		'noAvatarSet': 'Nie ustawiono awatara',
		'remove': 'Skasuj',
		'check': 'Sprawdź',
		'applySetting': 'Zatwierdź',
		'avatarFileInfo': 'URL powinien prowadzić bezpośrednio do obrazka (png, gif, jpeg).',
		'browserTooOldForAvatars': 'Twoja przeglądarka jest zbyt stara, aby obsłużyć wygodniejsze ustawianie awatarów.',
		'registerNickForAvatars': 'Zarejestruj nicka i potwierdź adres e-mail, aby uzyskać dostęp do wygodniejszego ustawiania awatarów.',
		'currentAvatar': 'Bieżący awatar',
		'youAcceptToStoreTheData': 'Klikając "Zatwierdź" wyrażasz zgodę na przechowywanie podanych danych na serwerach ',
		'addressMustStartWithHttps': 'Adres musi zaczynać się od "https://"!',
		'preview': 'Podgląd',
		'acceptPreview': 'Podgląd powyżej. Jeśli widać obrazek, możesz go zatwierdzić.',
		'noFileSelected': 'Nie wybrano pliku!',
		'processing': 'Trwa przetwarzanie, czekaj...',
		'failedToSendImageWithResponse': 'Błąd wysyłania obrazka. Odpowiedź serwera: ',
		'failedToSendImage': 'Nie udało się przesłać obrazka. Upewnij się, że plik nie jest zbyt duży, i spróbuj ponownie później.',
		'areYouSureToDeleteAvatar': 'Czy usunąć awatar ',
		'deleteAvatarQ': 'Czy usunąć bieżący awatar?',
		'failedToDeleteImageWithResponse': 'Błąd kasowania obrazka. Odpowiedź serwera: ',
		'failedToDeleteImage': 'Nie udało się skasować awatara. Spróbuj ponownie później.',
		'topicIsNotSet': 'Nie ustawiono tematu.',
		'changeChannelTopic': 'Zmodyfikuj temat kanału:',
		'changeTopicSubmit': 'Zmień temat',
		'youCanCopyCodesToTopic': 'Do tematu możesz skopiować kody formatowania wstawione w pole wiadomości.',
		'setBy': 'Założony przez',
		'date': 'Data',
		'appliesTo': 'Dotyczy',
		'mask': 'Maska',
		'listOf': 'Lista ',
		'onChannel': ' na kanale ',
		'listIsEmpty': 'Lista jest pusta.',
		'ofBans': 'banów',
		'ofExcepts': 'wyjątków',
		'ofInvites': 'zaproszeń',
		'allEmoticons': 'Wszystkie emotikony',
		'weekdays': [ 'Niedziela', 'Poniedziałek', 'Wtorek', 'Środa', 'Czwartek', 'Piątek', 'Sobota' ],
		'months': [ 'sty', 'lut', 'mar', 'kwi', 'maj', 'cze', 'lip', 'sie', 'wrz', 'paź', 'lis', 'gru' ],
		'show': 'Pokaż',
		'hide': 'Ukryj',
		'aPicture': ' obrazek',
		'aVideo': ' film',
		'linkCanBeUnsafe': 'Link może być niebezpieczny, czy na pewno chcesz go otworzyć?',
		'confirmJoin': 'Czy chcesz dołączyć do wybranego kanału?',
		'reconnect': 'Połącz ponownie',
		'lostNetworkConnection': 'Utracono połączenie z siecią.',
		'disconnected': 'Rozłączono',
		'msgNotice': 'Komunikat',
		'passwordNotGiven': 'Nie podałeś hasła!',
		'reconnectingWait': 'Ponowne łączenie, czekaj...',
		'connecting': 'Łączenie',
		'pingTimeout': 'Przekroczony czas odpowiedzi serwera',
		'nickNoLongerInUse': 'I już nie jest: usunąłem go używając Twojego hasła :)',
		'connectingTooLong': 'Łączenie trwa zbyt długo. Możesz poczekać lub spróbować jeszcze raz.',
		'connectingTookTooLong': 'Zbyt długi czas łączenia',
		'connectingWaitHtml': 'Poczekaj, trwa łączenie...<br />Nie używaj teraz przycisku "Wstecz" ani "Odśwież".',
		'errorLoadingData': 'Błąd wczytywania danych z ciasteczek. Wpisz dane.',
		'mustGiveNick': 'Musisz podać nicka!',
		'mustGiveChannel': 'Musisz podać kanał!',
		'badCharsInNick': 'Nick zawiera niedozwolone znaki!',
		'badNickStart': 'Nick nie może zaczynać się od cyfry ani minusa!',
		'spaceInPassword': 'Hasło nie powinno zawierać spacji!',
		'badCharsInChan': 'Kanał zawiera niedozwolone znaki!',
		'information': 'Informacja',
		'youCanDisableAutoconnect': 'Możesz wyłączyć automatyczne łączenie, na przykład w celu zmiany danych, klikając na ikonę ustawień w prawym górnym rogu, i odznaczając pole "Automatyczne łączenie".',
		'areYouSureToChangeTopicOf': 'Czy zmienić temat dla ',
		'itCantBeUndone': 'Nie można tego cofnąć.',
		'clickForWholeTopic': 'Kliknij aby zobaczyć cały temat',
		'textTooLongForSingleLine': 'Wpisany tekst nie zmieści się w jednej linijce. Czy na pewno chcesz go wysłać?',
		'textStartsWithSpaceAndSlash': 'Wpisany tekst zaczyna się od znaku "/", ale poprzedzonego spacją. Aby uniknąć pomyłki, wybierz, co chcesz zrobić.',
		'sendMessage': 'Wyślij wiadomość',
		'joinTo': 'Dołącz do ',
		'cancel': 'Anuluj',
		'runCommand': 'Wykonaj polecenie',
		'messageStartsWithHash': 'Wpisana wiadomość wygląda jak nazwa kanału IRC. Podawanie nazw kanałów na innych kanałach jest często uznawane jako spam. Aby uniknąć pomyłki, wybierz, co chcesz zrobić.',
		'changeSettings': 'Zmień ustawienia',
		'cantPMBecauseIgnoring': 'Nie możesz rozmawiać prywatnie z tym użytkownikiem, ponieważ jest na Twojej liście ignorowanych.',
		'giveForNick': 'Daj użytkownikowi ',
		'temporaryPrivilegesOnChan': ' bieżące uprawnienia na kanale ',
		'selectOption': 'Wybierz opcję',
		'voicePrivilege': 'VOICE (Uprawnienie do głosu)',
		'halfopPrivilege': 'HALFOP (Pół-operator kanału)',
		'opPrivilege': 'OP (Operator kanału)',
		'sopPrivilege': 'PROTECT/SOP (Administrator, ochrona przed kopnięciem)',
		'founderPrivilege': 'FOUNDER (Właściciel kanału)',
		'chanservPrivilegesOnChan': ' uprawnienia w ChanServ (na stałe) na kanale ',
		'youNeedServicePrivileges': '(musisz posiadać odpowiedni dostęp do serwisów)',
		'selectAvailableOption': 'Wybierz jedną z opcji!',
		'administrationOf': 'Zarządzanie ',
		'removeFromNick': 'Odbierz użytkownikowi ',
		'completelyRemoveNick': 'Usuń całkowicie użytkownika ',
		'fromChanservPrivilegesOnChan': ' z listy uprawnień w ChanServ (na stałe) na kanale ',
		'dontRemove': 'Nie, nie usuwaj',
		'yesRemove': 'Tak, usuń',
		'changeChannelModesOf': 'Zmień tryby kanału ',
		'character': 'Litera',
		'description': 'Opis',
		'inviteSomeone': 'Zaproś',
		'inviteUserTo': 'Zaproś użytkownika na ',
		'requestsInvitationTo': ' prosi o dostęp na ',
		'requestForInvitation': 'Prośba o dostęp',
		'kickUser': 'Wyrzuć użytkownika ',
		'fromChannel': ' z kanału ',
		'giveKickReason': 'Możesz podać powód dla KICKa, który zostanie wyświetlony dla wszystkich użytkowników kanału.',
		'doKick': 'Wyrzuć',
		'quitMessage': 'Wiadomość pożegnalna: ',
		'defaultQuitMessage': 'Użytkownik rozłączył się',
		'disconnect': 'Rozłącz',
		'ircQuit': 'Wyjście z IRC',
		'hasSet': 'ustawił ',
		'hasRemoved': 'zdjął ',
		'gave': 'dał ',
		'taken': 'odebrał ',
		'forUser': ' dla',
		'alreadyConnectedAs': 'Masz już otwartą bramkę w innej karcie przeglądarki i jesteś połączony jako ',
		'cantOpenMultipleInstances': 'Nie można otworzyć drugiej bramki.',
		'goToTabToJoin': 'Przejdź do tamtej karty, aby wejść na ',
		'alreadyConnected': 'Już połączony!',
		'otherTabWantsToJoin': 'Inna karta chce dołączyć do kanału ',
		'join': 'Dołącz',
		'confirm': 'Potwierdź',
		'channelList': 'lista kanałów',
		'hideList': 'schowaj listę',
		'insertFormatCodes': 'Wstaw kody formatowania',
		'hideFormatting': 'Schowaj formatowanie',
		'cantSendNoConnection': 'Nie możesz teraz wykonać komendy ani wysłać wiadomości, ponieważ nie masz połączenia z IRC.',
		'connectionNotAllowedHtml': '<p>Serwer nie zezwolił na to połączenie. Prawdopodobnie Twój adres IP został zbanowany.</p><p>Jeśli masz pewność, że nie zrobiłeś(aś) nic złego (sprawdź <a href="' + mainSettings.rulesUrl + '" target="_blank">regulamin</a>), spróbuj następujących kroków:'+
			'<ul>'+
			'<li>Wyłącz usługi typu VPN, Proxy, TOR. Użytkownicy tych usług tak często dokonują nadużyć, że PIRC nie zezwala im na dostęp.</li>'+
			'<li>Zresetuj swój router. Być może Twój dostawca internetu przypadkowo przypisał Tobie adres, za pomocą którego ktoś inny zrobił kiedyś coś złego.</li>'+
			'<li>Skontaktuj się z administracją PIRC pod adresem e-mail ' + mainSettings.adminMail + '</li>',
		'noAccessToNetwork': 'Brak dostępu',
		'listIsEmpty': 'Lista jest pusta.',
		'listOfIgnoredUsers': 'Lista ignorowanych użytkowników',
		'channelSmall': 'kanał',
		'privateDiscussionSmall': 'rozmowa prywatna',
		'addListEntry': 'Dodaj wpis do listy',
		'privateMessages': 'Wiadomości prywatne',
		'channelMessages': 'Wiadomości na kanale',
		'add': 'Dodaj',
		'operationFailed': 'Operacja nieudana.',
		'noMaskGiven': 'Nie wpisano maski!',
		'maskCantContainSpaces': 'Maska nie może zawierać spacji!',
		'neitherChannelNorQuerySelected': 'Nie zaznaczono ani kanału ani query!',
		'cantIgnoreAllInChannels': 'Nie możesz ignorować wszystkich nicków na kanałach!',
		'cantIgnoreNetworkService': 'Nie możesz ignorować usługi sieciowej!',
		'ignorePMs': 'Ignoruj wiadomości prywatne',
		'ignoreChanMsgs': 'Ignoruj wiadomości na kanałach',
		'isIgnoredByWildcards': 'Ten użytkownik jest ignorowany za pomocą reguł ogólnych.',
		'manageIgnored': 'Zarządzaj ignorowanymi nickami',
		'ignoreUserNick': 'Ignoruj użytkownika ',
		'logIn': 'Zaloguj',
		'yourPassword': 'Twoje hasło:',
		'saveThisPassword': 'Zapisz to hasło',
		'newNick': 'Nowy nick:',
		'changeNick': 'Zmień nick',
		'youHaveLimitedTimeToLogInHtml': 'Masz <span id="nickserv_timer">określony czas</span> na zmianę nicka, potem zostanie zmieniony siłą. Bez obaw: gdy wpiszesz poprawne hasło, to odzyskasz swojego nicka.',
		'second': 'sekund',
		'second1': 'ę',
		'second2': 'y',
		'maskBannedMask': /^Zbanowano maskę .(.*). \(dla .(.*).\)$/i,
		'youreIdentifiedMask': /^Hasło przyjęte - jesteś zidentyfikowany\(a\)\.$/i,
		'nickNotRegisteredMask': /^Nick [^ ]+ nie jest zarejestrowany\.$/i,
		'invalidPasswordMask': /^Nieprawidłowe hasło\.$/i,
		'givenPasswordForNick': 'Podane hasło do nicka ',
		'isInvalidChangeNick': ' jest błędne. Możesz spróbować ponownie lub zmienić nicka.',
		'registeredProtectedNickMask': /^Ten nick jest zarejestrowany i chroniony\.( Jeśli należy do Ciebie,)?$/i,
		'selectedNick': 'Wybrany nick ',
		'isRegisteredChangeNick': ' jest zarejestrowany. Musisz go zmienić lub podać hasło.',
		'identifyMask': /^Zidentyfikuj się pisząc: /i,
		'nickBelongingToYouMask': /^jeśli nick należy do Ciebie, w przeciwnym razie zmień go\.$/i,
		'notUsedByServicesMask': /^Nick .* nie jest zajęty przez serwisy\.$/i,
		'notCurrentlyUsedMask': /^Nick .* nie jest aktualnie używany\.$/i,
		'loginPromptMask': /^wpisz .\/msg NickServ IDENTIFY .hasło..\. W przeciwnym wypadku$/i,
		'selectOtherNickMask': /^wybierz proszę inny nick.$/i,
		'accessDeniedMask': /^Odmowa dostępu\.$/i,
		'passwordForUsedNick': 'Podane hasło do zajętego nicka ',
		'isInvalidRetryOrChangeNick': 'jest błędne. Możesz spróbować ponownie odzyskać nicka, podając poprawne hasło, lub go zmienić.',
		'nickRemovedFromNetworkMask': /^Nick został usunięty z sieci\.$/i,
		'servicesReleasedNickMask': /^Serwisy właśnie zwolniły.*nicka.*\.$/i,
		'youHaveTimeToChangeNickMask': /^Masz (.*) na zmianę nicka, potem zostanie zmieniony siłą\.$/i,
		'ifYouDontChangeMask': /^Jeśli go nie zmienisz w ciągu (.*), zostanie zmieniony siłą\.$/i,
		'oneMinute': 'jedną minutę',
		'n60seconds': '60 sekund(y)',
		'n1minute': '1 minuta(y)',
		'n1minute2': '1 minuta',
		'n60seconds2': '60 sekund',
		'n20seconds': '20 sekund',
		'n20seconds2': '20 sekund(y)',
		'eachFunctionNeedsPermissions': 'Uwaga: użycie każdej z funkcji wymaga odpowiednich uprawnień.',
		'banUser': 'Banuj użytkownika',
		'kickUser': 'Kop użytkownika',
		'nickOrMask': 'Nick/maska',
		'reason': 'Powód',
		'channelDescription': 'Opis kanału',
		'registerChannel': 'Zarejestruj kanał',
		'checkUserChanservStatus': 'Sprawdź status użytkownika w ChanServ',
		'displayAccessList': 'Wyświetl listę dostępową',
		'deleteUserFromAccessList': 'Usuń użytkownika z listy dostępowej',
		'chanservCommandsOn': 'Polecenia ChanServ na ',
		'workInProgress': 'Funkcja w przygotowaniu - niektóre opcje mogą nie działać, a lista może być niepełna!',
		'showBotList': 'Pokaż listę botów',
		'nickChosenFromBotList': 'Nick (wybrany z BOTLIST)',
		'assignBotToChan': 'Przypisz bota do kanału',
		'removeBotFromChan': 'Usuń bota z kanału',
		'message': 'Wiadomość',
		'sendActionToChan': 'Wyślij wiadomość na kanał (/me wiadomość)',
		'sendMessageToChan': 'Wyślij wiadomość na kanał',
		'botservCommandsOn': 'Polecenia BotServ na ',
		'argumentRequiredForCmd': 'Wymagany argument dla polecenia ',
		'banAndKickUserFrom': 'Zbanuj i wyrzuć użytkownika ',
		'noAutoUnban': 'Nie zdejmuj bana automatycznie',
		'unban1Day': 'Zdejmij bana automatycznie po 1 dniu',
		'unban1Hour': 'Zdejmij po godzinie',
		'unban1Month': 'Zdejmij po miesiącu',
		'doBan': 'Zbanuj',
		'youNeedRegisteredNickToUseThis': 'Musisz mieć zarejestrowanego nicka aby użyć tej opcji!',
		'change': 'Zmień',
		'nickChange': 'Zmiana nicka',
		'noNickGiven': 'Nie wpisano nicka!',
		'nickCantContainSpaces': 'Nick nie może zawierać spacji!',
		'password': 'Hasło:',
		'repeatPassword': 'Powtórz hasło:',
		'email': 'E-mail:',
		'emailNeeded': 'Adres e-mail jest potrzebny do potwierdzenia rejestracji, oraz aby w przyszłości odzyskać hasło.',
		'register': 'Zarejestruj',
		'registrationOfNick': 'Rejestracja nicka ',
		'passwordsNotMatching': 'Podane hasła nie są zgodne!',
		'mailNotGiven': 'Nie wpisano adresu e-mail!',
		'badEmail': 'Podany e-mail jest błędny!',
		'youHaveToWaitAnother': 'Musisz zaczekać jeszcze ',
		'secondsToRegisterNick': ' sekund(y), zanim będzie możliwa rejestracja nicka.',
		'thisCommandWillRequestVhost': 'To polecenie wyśle prośbę do administratorów o ustawienie Tobie podanego vhosta.',
		'newVhost': 'Nowy vHost: ',
		'lettersDigitsDot': 'vHost może zawierać tylko litery i cyfry, i musi mieć w środku co najmniej jedną kropkę.',
		'proceed': 'Wykonaj',
		'settingOfVhost': 'Ustawianie vhosta',
		'user': 'użytkownik',
		'multipleUsers': 'ów',
		'chanOp': 'op',
		'browserTooOldQuit': 'Za stara przeglądarka!',
		'registered': 'Zarejestrowany',
		'unRegistered': 'Niezarejestrowany',
		'query': 'Rozmowa prywatna',
		'softwareVersion': 'Wersja oprogramowania',
		'channelAdministration': 'Administracja',
		'kickFromChannel': 'Wyrzuć z kanału',
		'banUsingChanserv': 'Banuj (ChanServ)',
		'givePrivileges': 'Daj uprawnienia',
		'takePrivileges': 'Odbierz uprawnienia',
		'loggedInAs': 'Zalogowany jako ',
		'userIsAway': 'Ten użytkownik jest nieobecny',
		'reason': 'powód',
		'userIsIrcop': 'Ten użytkownik jest IRCOperatorem',
		'userIsBot': 'Ten użytkownik jest botem',
		'nickIsRegistered': 'Ten nick jest zarejestrowany',
		'userIsLoggedIntoAccount': 'Ten użytkownik jest zalogowany do konta ',
		'closeQuery': 'Zamknij rozmowę prywatną',
		'leftChannel': 'Opuścił kanał',
		'leaveChannel': 'Wyjdź z kanału',
		'channelOptions': 'Opcje kanału',
		'autoJoinThisChannel': 'Automatycznie wchodź na ten kanał',
		'enable': 'Włącz',
		'disable': 'Wyłącz',
		'clearMessageWindow': 'Wyczyść okno rozmowy',
		'refreshNickList': 'Odśwież listę nicków',
		'administrativeActions': 'Akcje administracyjne',
		'banList': 'Lista banów (b)',
		'exceptListHint': 'Znajdujący się na liście nie są obejmowani przez bany',
		'exceptList': 'Lista wyjątków b (e)',
		'invexListHint': 'Znajdujący się na liście nie potrzebują zaproszenia, gdy jest ustawiony tryb +i',
		'invexList': 'Lista wyjątków i (I)',
		'channelModes': 'Tryby kanału',
		'inviteToChannel': 'Zaproś na kanał',
		'chanservCommands': 'Polecenia ChanServ',
		'botservCommands': 'Polecenia BotServ',
		'dontWantPrivateMessages': 'Nie chcę otrzymywać wiadomości prywatnych:',
		'dontWantAnyMessages': 'żadnych (tryb +D)',
		'dontWantFromUnregistered': 'od niezarejestrowanych użytkowników (tryb +R)',
		'dontShowAvatars': 'Nie pokazuj avatarów (stary wygląd)',
		'setOwnAvatar': 'Ustaw własny avatar',
		'dontShowJoinsQuits': 'Nie pokazuj wiadomości PART/JOIN/QUIT (wejścia/wyjścia z kanałów)',
		'dontShowNickChanges': 'Nie pokazuj informacji o zmianach nicków',
		'dontShowModes': 'Nie pokazuj wiadomości MODE (zmian trybów)',
		'tabListOnBottom': 'Listę zakładek pokazuj na dole strony',
		'showHostnames': 'Pokazuj nazwy hosta użytkowników',
		'autoReconnect': 'Automatycznie łącz ponownie po rozłączeniu',
		'unsafeLinkWarnings': 'Pokazuj ostrzeżenia o niebezpiecznych linkach',
		'darkTheme': 'Ciemny motyw bramki (eksperymentalny)',
		'colorNicks': 'Koloruj nicki w oknie rozmowy',
		'newMsgSound': 'Informuj dźwiękiem o nowej wiadomości',
		'showEmoji': 'Wyświetlaj emoji w miejsce emotikon tekstowych (na przykład "<g-emoji fallback-src="/styles/emoji/1f642.png">🙂</g-emoji>" w miejsce ":)")',
		'sendEmoji': 'Wysyłaj powyższe emoji na IRC',
		'monospaceFont': 'Wyświetlaj treść rozmowy fontem o stałej szerokości',
		'autoDisconnect': 'Automatycznie rozłączaj przy zamykaniu strony',
		'autoConnect': 'Automatyczne łączenie (bez podawania nicka i hasła)',
		'backlogCount':  'Ilość linii w historii rozmów z poprzedniej wizyty',
		'popupWindow': 'Wyskakujące okienko',
		'statusTab': 'Zakładka statusu',
		'manageIgnored': 'Zarządzaj ignorowanymi nickami',
		'allRightsReserved': 'Wszelkie prawa zastrzeżone',
		'statusTabName': 'Status',
		'extendChannelList': '⮙ lista kanałów ⮙',
		'nickOptions': 'Opcje nicka',
		'registerNick': 'Zarejestruj nicka',
		'privateMessagesBlocking': 'Blokowanie wiadomości prywatnych',
		'requestAVhost': 'Poproś o vhosta',
		'showChannelsWithAccess': 'Pokaż kanały, na których masz stałe uprawnienia',
		'showAutojoinChannels': 'Pokaż kanały, na które automatycznie wchodzisz',
		'insertFormatCodes': '⮛ Wstaw kody formatowania ⮛',
		'insertColorCode': 'Wstaw kod koloru',
		'insertSpecialCode': 'Wstaw kod specjalny',
		'turnOffColor': 'Wyłącz kolor',
		'boldText': 'Pogrubienie',
		'reverseColors': 'Odwróć kolory',
		'italicText': 'Pochylenie',
		'underscoreText': 'Podkreślenie',
		'clearFormats': 'Czyść wygląd',
		'emoticons': 'Emotikony',
		'showAllAvailable': 'Pokaż wszystkie dostępne',
		'thisCanTakeTime': '(to może potrwać)',
		'engineeringSymbols': 'Symbole inżynierskie',
		'version': 'Wersja',
		'statusWindow': 'Okno statusu',
		'noticeDisplay': 'Sposób wyświetlania wiadomości NOTICE',
		'connectingForTooLong': 'Łączenie z serwerem trwa zbyt długo, serwer bramki nie działa lub twoja przeglądarka nie funkcjonuje prawidłowo.<br />Spróbuj ponownie później lub spróbuj ',
		'channel': 'Kanał',
		'passwordIfRegistered': 'Hasło (jeżeli zarejestrowany)',
		'savePassword': 'Zapisz hasło',
		'saveAllAndDontShowAgain': 'Zapisz wszystkie dane i nie wyświetlaj ponownie tego okna',
		'connectToIRC': 'Połącz z IRC',
		'logon': 'Logowanie',
		'userClosedPage': 'Użytkownik zamknął stronę',
		'youreStillConnected': 'Jesteś nadal połączony z IRCem. Kliknij "Zostań na stronie" a następnie "Rozłącz" w okienku poniżej aby się rozłączyć przed wyjściem.',
		'cookiesDisabledHtml': 'Twoja przeglądarka ma wyłączoną obsługę ciasteczek. Niektóre funkcje bramki mogą działać nieprawidłowo.<br /><input type="button" onclick="conn.dispConnectDialog();" value="Kontynuuj" />',
		'websocketDisabledHtml': 'Twoja przeglądarka nie obsługuje WebSocket. Nie można uruchomić bramki.<br>Spróbuj ',
		'close': 'Zamknij',
		'none': 'brak',
		'disconnectOnRequest': 'Rozłączono z IRC na życzenie.',
		'youHaveToGiveNewNick': 'musisz podać na co chcesz zmienić swój obecny nick.',
		'youHaveToGiveQueryNick': 'musisz podać nick osoby o której chcesz zdobyć informację.',
		'youHaveToGivePMNick': 'musisz podać nick osoby z którą chcesz rozpocząć prywatną rozmowę',
		'youHaveToGiveChanFirstArg': 'musisz podać kanał jako pierwszy argument.',
		'youHaveToGiveChannelToJoin': 'musisz podać kanał, do którego chcesz dołączyć.',
		'youHaveToGiveInviteNickChannel': 'musisz podać nicka użytkownika, i nazwę kanału, na który chcesz go zaprosić.',
		'youHaveToGiveKnockChan': 'musisz podać kanał, do którego chcesz zapukać.',
		'youHaveToGiveMsgText': 'musisz podać treść wiadomości, którą chcesz wysłać.',
		'youHaveToGiveMsgNickText': 'musisz podać nick osoby do której chcesz napisać i tekst który chcesz jej wysłać.',
		'youHaveToGivePartChan': 'musisz podać kanał z którego chcesz wyjść jako pierwszy argument.',
		'youHaveToGiveKickChan': 'musisz podać kanał z którego chcesz wykopać tę osobę jako pierwszy argument.',
		'youHaveToGiveKickNick': 'musisz podać nick osoby którą chcesz wykopać jako pierwszy argument.',
		'youHaveToBeOnChan': 'musisz być na jakimś kanale aby użyć tej komendy.',
		'youHaveToGiveChannelToTakeGivePerms': 'musisz podać kanał, na ktorym chcesz dać/odebrać uprawnienia tej osobie.',
		'youHaveToGiveChannelAndNickToTakeGivePerms': 'musisz podać kanał na którym chcesz dać/odebrać uprawnienia, i nick osoby, której chcesz je dać.',
		'youHaveToGiveChanOrNick': 'musisz podać nick/kanał jako pierwszy argument',
		'privateMsgBlocking': 'Blokowanie wiadomości prywatnych',
		'settings': 'Ustawienia',
		'showUserHostTitle': 'Pokazuje informację user@host przy dołączaniu i opuszczaniu kanałów przez użytkowników',
		'linkInfoTitle': 'Ustawienie nie wpływa na linki, które są już wyświetlone',
		'noticeDisplayTitle': 'Gdy rozmowa prywatna jest już otwarta, to, niezależnie od tego ustawienia, tam pojawią się wszystkie NOTICE',
		'avatar': 'Avatar',
		'changeSizeTitle': 'Zmień rozmiar tekstu',
		'gatewayInfoTitle': 'Informacje o bramce',
		'disconnectWithIrc': 'Rozłącz z IRC',
		'tabTitle': 'Uzupełnij nick lub polecenie [Tab]',
		'emoticonsSymbolsTitle': 'Emotikony i symbole',
		'colorsFormattingTitle': 'Kolory i formatowanie',
		'enterTitle': 'Wyślij [Enter]',
		'textFormattingTitle': 'Formatowanie tekstu',
		'symbolsTitle': 'Symbole',
		'selectTextSizeTitle': 'Wybierz wielkość tekstu',
		'ignoreThis': 'Ignoruj',
		'topicOfChannel': 'Temat kanału ',
		'mode': 'tryb',
		'enterUrl': 'Podaj adres URL:',
		'selectAnImage': 'Wybierz obrazek:',
		'yes': 'Tak',
		'no': 'Nie',
		'messageNotDelivered': 'Ta wiadomość nie została dostarczona',
		'historyEntry': 'Historia rozmowy',
		'getMoreHistory': 'Pobierz więcej historii…'
	},
	'en': {
		'messagePatterns': {
			'nickChange': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> <span class="modeinfo">%s</span> is now known as <span class="modeinfo">%s</span></span></div>',
			'nickInUse': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick"><span class="symbolFont">✯</span> <span class="modeinfo">%s</span>: Nick is already in use.</span></div>',
			'badNick': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick"><span class="symbolFont">⮿</span> <span class="modeinfo">%s</span>: Nick is not available.</span></div>',
			'nickChangeOwn': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> You\'re now known as <span class="modeinfo">%s</span></span></div>',
			'joinOwn': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="join"><span class="symbolFont">🢡</span> You <i class="userhost">(%s!%s@%s)</i> joined <span class="modeinfo">%s</span>.</span></div>',
			'join': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="join"><span class="symbolFont">🢡</span> <b>%s</b> <i class="userhost">[%s@%s]</i> has joined <span class="modeinfo">%s</span>.</span></div>',
			'part': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="part"><span class="symbolFont">🢠</span> <b>%s</b> <i class="userhost">[%s@%s]</i> has left <span class="modeinfo">%s</span> [%s]</span></div>',
			'quit': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="part"><span class="symbolFont">🢠</span> <b>%s</b> <i class="userhost">[%s@%s]</i> has left IRC [%s]</span></div>',
			'partOwn': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="part"><span class="symbolFont">🢠</span> You left <span class="modeinfo">%s</span>. <a href="#" onclick="gateway.send(\'JOIN %s\')">Rejoin</a></span></div>',
			'channelMsg': '<div class="messageDiv %s" %s><div class="messageMeta">%s</div><div class="messageHeader"><span class="time">%s &nbsp;</span><span class="nick">&lt;<span %s>%s</span>&gt;%s</span></div><span class="msgText">%s</span></div>',
			'yourMsg': '<div class="messageDiv %s" %s><div class="messageMeta">%s</div><div class="messageHeader"><span class="time">%s &nbsp;</span><span class="yournick">&lt;<span %s>%s</span>&gt;%s</span></div><span class="msgText">%s</span></div>',
			'channelMsgHilight': '<div class="messageDiv %s" %s><div class="messageMeta">%s</div><div class="messageHeader"><span class="time">%s &nbsp;</span><span class="hilight"><span class="nick">&lt;%s&gt;%s</span></span></div><span class="msgText">%s</span></div>',
			'channelAction': '<div class="messageDiv %s" %s><span class="time">%s</span> &nbsp; ❇ <span class="nick"><span %s>%s</span></span> %s</div>',
			'yourAction': '<div class="messageDiv %s" %s><span class="time">%s</span> &nbsp; ❇ <span class="yournick"><span %s>%s</span></span> %s</div>',
			'channelActionHilight': '<div class="messageDiv %s" %s><span class="time">%s</span> &nbsp; ❇ <span class="hilight"><span class="nick">%s</span> %s</span></div>',
			'changeTopic': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> <span class="modeinfo">%s</span> changed channel topic to: %s</span></div>',
			'deleteTopic': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> <span class="modeinfo">%s</span> removed topic of <span class="modeinfo">%s</span></span></div>',
			'topic': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Topic of <span class="modeinfo">%s</span> is: %s</span></div>',
			'topicNotSet': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Topic of <span class="modeinfo">%s</span> is not set</span></div>',
			'topicTime': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Topic set by <span class="modeinfo">%s</span> [%s]</span></div>',
			'kick': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick"><span class="symbolFont">✀</span> <span class="modeinfo">%s</span> has kicked <span class="modeinfo">%s</span> from <span class="modeinfo">%s</span> [Reason: %s]</span></div>',
			'kickOwn': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick"><span class="symbolFont">✀</span> <span class="modeinfo">%s</span> kicked you from <span class="modeinfo">%s</span> [Reason: %s]</span></div>',
			'modeChange': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">🔧</span> <span class="modeinfo">%s</span> %s on channel <span class="modeinfo">%s</span></span></div>',
			'mode': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">🔧</span> Settings of channel <span class="modeinfo">%s</span>: %s</span></div>',
			'umode': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">🔧</span> Settings for user <span class="modeinfo">%s</span>: %s</span></div>',
			'creationTime': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Channel created: %s</span></div>',
			'startedQuery': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="join"><span class="symbolFont">🢡</span> Started talking with <span class="modeinfo">%s</span>. <a onclick="ignore.askIgnore(\'%s\');">Ignore this user</a> / <a onclick="disp.showQueryUmodes()">Private message blocking settings</a></span></div>',
			'queryBacklog': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="join"><span class="symbolFont">✯</span> Record of previous query with <span class="modeinfo">%s</span>:</span></div>',
			'channelBacklog': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Record of your previous visit on <span class="modeinfo">%s</span>:</span></div>',
			'channelBacklogEnd': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> End of record.</span></div>',
			'noSuchCommand': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">⮿</span> <span class="modeinfo">%s</span>: unknown command.</span></div>',
			'noSuchNick': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">⮿</span> <span class="modeinfo">%s</span>: there is no such nick nor channel</span></div>',
			'noSuchNickHistory': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">⮿</span> <span class="modeinfo">%s</span>: no history avalilable</span></div>',
			'noSuchChannel': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">⮿</span> <span class="modeinfo">%s</span>: no such channel</span></div>',
			'notOnChannel': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">⮿</span> <span class="modeinfo">%s</span>: you\'re not on this channel</span></div>',
			'alreadyOnChannel': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">⮿</span> %s: <span class="modeinfo">%s</span> already is on this channel</span></div>',
			'youQuit': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="part"><span class="symbolFont">✯</span> You left IRC</span></div>',
			'notConnected': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">⮿</span> You\'re not connected to IRC!</span></div>',
			'notEnoughParameters': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">⮿</span> <span class="modeinfo">%s</span>: Too few arguments.</span></div>',
			'cannotSendToChan': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick"><span class="symbolFont">⮿</span> Can\'t talk on <span class="modeinfo">%s</span>: %s. Message is not delivered.</span></div>',
			'cannotSendToUser': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick"><span class="symbolFont">⮿</span> Can\'t send to <span class="modeinfo">%s</span>: %s. Message is not delivered.</span></div>',
			'cannotJoin': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick"><span class="symbolFont">⮿</span> Can\'t join <span class="modeinfo">%s</span>: %s</span></div>',
			'noPerms': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick"><span class="symbolFont">⮿</span> No access.</span></div>',
			'notice': '<div class="messageDiv %s" %s><span class="time">%s</span> &nbsp; <span class="notice-nick"><b>-%s-</b></span><span class="userhost">(<span class="notice-nick">%s</span>@<span class="notice-nick">%s</span>)</span> <span class="notice">%s</span></div>',
			'serverNotice': '<div class="messageDiv" %s><span class="time">%s</span> &nbsp; <span class="notice-nick">Notice from server <b>%s</b>:</span> <span class="notice">%s</span></div>',
			'yourNotice': '<div class="messageDiv %s" %s><span class="time">%s</span> &nbsp; <span class="notice"><b>-NOTICE/%s-</b> %s</span></div>',
			'yourServiceCommand': '<div class="messageDiv %s" %s><span class="time">%s</span> &nbsp; <span class="notice"><b>[%s → %s]</b> %s</span></div>',
			'notEnoughParams': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">⮿</span> <span class="modeinfo">%s</span>: too few arguments: %s</span></div>',
			'motd': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="motd"><span class="symbolFont">✯</span> %s</span></div>',
			'SaslAuthenticate': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="sinfo"><span class="symbolFont">🔧</span> %s</span></div>',
			'ctcpRequest': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> <span class="modeinfo">%s</span> is sending CTCP REQUEST: %s</span></div>',
			'ctcpReply': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="notice"><span class="symbolFont">✯</span> <b>CTCP REPLY from %s:</b> %s</span></div>',
			'chanListElement': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="notice"><span class="symbolFont">✯</span> <b><a href="#" onClick="gateway.send(\'JOIN %s\')">%s</a></b> (%s) - %s </span> </div>',
			'chanListElementHidden': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="notice"><span class="symbolFont">✯</span> <b>(channel hidden)</b> (%s) - (topic hidden) </span> </div>',
			'error': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"> <span class="symbolFont">⮿</span> Disconnected from server: %s</span></div>',
			'existingConnection': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Connection already exists, joining it.</span></div>',
			'away': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">🍵</span> <span class="modeinfo">%s</span> received your message, but is now away: %s</span></div>',
			'yourAwayEnabled': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">🍵</span> You\'re now marked as being away</span></div>',
			'yourAwayDisabled': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">🍵</span> You\'re no longer marked as away</span></div>',
			'yourInvite': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> You invited user <span class="modeinfo">%s</span> to join <span class="modeinfo">%s</span></span></div>',
			'knocked': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> You knocked on <span class="modeinfo">%s</span>, wait from invitation from an oper. Remember that currently there may be no operators available. In such case please wait several tens of minutes and try again.</span></div>',
			'listShown': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Channel list will appear in the Status tab.</span></div>',
			'channelIgnoreAdded': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Added <b>%s</b> to channel ignore list.</span></div>',
			'channelIgnoreRemoved': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Removed <b>%s</b> from channel ignore list.</span></div>',
			'queryIgnoreAdded': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Added <b>%s</b> to private message ignore list.</span></div>',
			'queryIgnoreRemoved': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Removed <b>%s</b> from private message infore list.</span></div>',
			'ignoreListStart': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Ignore list:</span></div>',
			'ignoreListEnd': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> End of list.</span></div>',
			'ignoreListEmpty': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Ignore list is empty.</span></div>',
			'ignoreListItem': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"><span class="symbolFont">✯</span> Type: <b>%s</b>, mask: <b>%s</b></span></div>',
			'netsplit': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="part"><span class="symbolFont">🢠</span> <span class="netsplit">Netsplit</span> quits: %s</span></div>',
			'netjoin': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="join"><span class="symbolFont">🢡</span> <span class="netjoin">Netsplit</span> over, joins: %s</span></div>',
			'displayedHost': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="sinfo"><span class="symbolFont">🔧</span> Your host is now visible as %s</span></div>',
			'invalidMode': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick"><span class="symbolFont">⮿</span> Invalid mode "%s"</span></div>',
			'unimplemented': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="sinfo"><span class="symbolFont">✯</span> %s</span></div>',
			'unimplementedError': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick"><span class="symbolFont">⮿</span> %s</span></div>'
		},
		'SASLLogin': 'SASL: logging into account ',
		'SASLLoginAttempt': 'SASL login attempt...',
		'recoverErrorHtml': '<h2>General fault</h2><p>Another session has disconnected you using a RECOVER command. Maybe you have more than one client instance open?</p>',
		'error': 'Error',
		'serverClosedConnection': 'Server closed the connection',
		'informations': 'Information',
		'inviting': 'invites you to channel',
		'enter': 'Join',
		'ignore': 'Ignore',
		'invitation': 'Invitation',
		'userSoftware': 'User software of ',
		'networkServiceMessage': 'Notice from a network service',
		'privateNoticeFrom': 'Private notice from ',
		'privateNoticeFromServer': 'Private notice from server ',
		'realNickname': 'Real IRC nickname',
		'notLoggedIn': 'Not logged in',
		'loggedIn': 'Logged in',
		'loggedInAs': 'Logged in as ',
		'warning': 'Warning',
		'yourCurrentNickIs': 'Your current nickname is ',
		'notPresent': 'Away',
		'isNotPresent': ' is away: ',
		'nickRegistered': 'This nickname is registered',
		'fullMask': 'Full mask',
		'realname': 'Real name',
		'userInformation': 'Information about ',
		'server': 'Server',
		'seen': 'Seen',
		'ircop': 'NETWORK OPERATOR',
		'networkService': 'Network service',
		'previousVisitsBy': 'Previous visits of ',
		'signedOn': 'Signed on',
		'idle': 'Idle',
		'hoursShort': 'h',
		'minutesShort': 'min',
		'secondsShort': 'sec',
		'joinChannel': 'Join channel',
		'channels': 'Channels',
		'isConnectingFrom': 'Is connecting from: ',
		'noTopic': 'no topic is set',
		'fullList': 'Complete list',
		'refresh': 'Refresh',
		'largestChannels': 'Largest channels',
		'accountName': 'Account name',
		'isBotHtml': 'This user is a <b>bot</b>',
		'nickListFor': 'Nick list for dla ',
		'noSuchNickChannel': 'Can\'t perform requested action. There is no such nick nor channel present',
		'noSuchObject': 'Can\'t perform requested action. No such object',
		'noSuchChannel': 'Can\'t perform requested action. No such channel',
		'needVoice': 'You need voice to talk on this channel now',
		'youreBanned': 'You\'re banned',
		'colorsForbidden': 'Messages containing color codes are forbidden on this channel',
		'noExternalMsgs': 'You have to be on this channel in order to send to it',
		'registeredNickRequired': 'You need to have your nickname registered to talk on this channel now',
		'serverMessageIs': 'Message from the server: ',
		'cantSendMessageTo': 'Can\'t send message to ',
		'recentVisitsForNickNotFound': 'Previous visits of following nick not found: ',
		'isCurrentlyNotAvailable': ' is not available. Please retry after a few minutes.',
		'nickname': 'Nickname',
		'isAlreadyUsedBySomeone': ' is being used by someone else.',
		'youreNotOnChannel': ' you\'re not on this channel.',
		'isAlreadyOnChannel': ' already is on this channel.',
		'cantChangeNickMessageHtml': 'Can\'t change nick.<br>Message from the server: ',
		'invalidMode': 'Invalid mode',
		'cantJoin': 'Can\'t join channel',
		'inviteRequired': 'You need to be invited to join.',
		'inviteRequiredShort': 'Channel requires an invitation.',
		'askOpersForEntry': 'Ask operators for entry',
		'entryRequest': 'Please allow me to join',
		'needValidPassword': 'You have to provide a valid password',
		'passwordRequired': 'Passowrd required',
		'registerYourNickToJoin': 'This channel requires you to have a registered nickname. Please use the instructions NickServ has sent to you.',
		'registeredNickRequiredForChan': 'Registered nick required',
		'cantKnock': 'Can\'t knock on channel.',
		'noAccess': 'no access',
		'notEnoughPrivileges': 'You don\'t have enough privileges to perform requested action.',
		'cantSendPMTo': 'Can\'t send private message to ',
		'cantSendPM': 'Can\'t send private message.',
		'yourNickMustBeRegistered': 'Your nickname must be registered',
		'userAcceptsPMsOnlyFromRegistered': 'This user accepts messages from registered users only.',
		'SSLRequired': 'This channel requires a secure connection.',
		'noPermsForAction': 'You don\'t have correct permissions to perform requested action',
		'hasSecureConnection': 'Is using a Secure Connection',
		'weAreLoggedInAs': 'Logged in as ',
		'SASLLoginSuccess': 'SASL: login successful.',
		'SASLLoginFail': 'SASL: login failed!',
		'suppliedNickPassword': 'Given password for nickname ',
		'passwordInvalidTryAgain': ' is incorrect. You can try again or change your nick.',
		'SASLNotLoggedIn': 'SASL: not logged in.',
		'gatewayVersionIs': 'WWW PIRC.PL client, version ',
		'versionWithAddons': ', with add-ons: ',
		'runningOn': 'on',
		'unknown': 'Unknown',
		'chStatusInfo': [ 'Unregistered', 'Voice', 'Half-op', 'Operator', 'Admin', 'Owner', 'Registered' ],
		'modes': {
			/* unrealircd mode comments */
			'changeableSingle': [
				['m', 'Moderated channel'],
				['i', 'Invite-only'],
				['s', 'Hidden'],
				['R', 'Only for registered users'],
				['N', 'Nick changes forbidden'],
				['Q', 'Kicks forbidden'],
				['M', 'Voice or registered nick required to speak'],
				['t', 'Only an operator can change the topic'],
				['n', 'Can\'t talk without joining the channel'],
				['D', 'Users will appear on the list only as they start speaking']
			],
			'changeableArg': [
				['k', 'Channel password'],
				['l', 'Maximum user count']
			],
			'chModeInfo': {
				'q': 'owner status',
				'a': 'admin status',
				'o': 'operator status',
				'h': 'half-op status',
				'v': 'voice',
				'k': 'password:',
				'b': 'ban for',
				'e': 'ban exception for',
				'I': 'permanent invitation for',
				'f': 'flood protection:',
				'p': 'private mode',
				's': 'hidden mode',
				'm': ['moderation', 'channel moderated'],
				'n': 'no external messages',
				't': ['topic protection', 'protected topic'],
				'i': 'invite-only',
				'r': ['registration', 'registered'],
				'R': 'registered-only',
				'c': ['color blocking', 'color blocked'],
				'O': 'O mode',
				'Q': ['kick blocking', 'kick blocked'],
				'K': ['knock blocking', 'knock blocked'],
				'V': ['invite blocking', 'invites blocked'],
				'C': ['CTCP blocking', 'CTCP blocked'],
				'z': 'secure users only',
				'N': ['nick change blocking', 'nick change blocked'],
				'S': 'color stripping',
				'M': ['unregistered moderation', 'unregistered are moderated'],
				'T': ['NOTICE blocking', 'NOTICE blocked'],
				'G': 'mode G',
				'D': 'mode D: users will be visible on the list only after they start speaking',
				'd': 'mode d',
				'L-add': 'redirection to channel',
				'L-remove': 'redirection to another channel',
				'l-add': 'user limit to',
				'l-remove': 'user limit',
				'H-add': 'channel history storage',
				'H-remove': 'channel history storage'
			},
			'chStatusNames': {
				'q': 'owner',
				'a': 'admin',
				'o': 'op',
				'h': 'halfop',
				'v': 'voice'
			},
		},
		'newMessage': 'New message',
		'loading': 'Loading',
		'loadingWait': 'Loading, please wait...',
		'outdatedBrowser': 'Outdated browser',
		
		'': 'Your browser is outdated and not supported. You need to update the Internet Explorer browser to version 9 or higher, or use current version of a different browser (Firefox, Opera, Chrome, Safari).<br />If you already have Internet Explorer 9 or higher and you are seeing this message, please disable the "Quirks mode" for this page.',
		'noAvatarSet': 'No avatar set',
		'remove': 'Remove',
		'check': 'Check',
		'applySetting': 'Apply',
		'avatarFileInfo': 'URL needs to point to an image (png, gif, jpeg).',
		'browserTooOldForAvatars': 'Your browser is too old to support easy avatar setting.',
		'registerNickForAvatars': 'Register your nick and confirm e-mail address to get access to easier avatar setting.',
		'currentAvatar': 'Current avatar',
		'youAcceptToStoreTheData': 'By clicking "Apply" you approve storage of given data by ',
		'addressMustStartWithHttps': 'Adddress must start with "https://"!',
		'preview': 'Preview',
		'acceptPreview': 'Preview is available above. If the image displays correctly, you can apply the setting.',
		'noFileSelected': 'File not selected!',
		'processing': 'Processing, please wait...',
		'failedToSendImageWithResponse': 'Failed to send the image. Server answers: ',
		'failedToSendImage': 'Failed to send the image. Ensure that it is not too large and try again later.',
		'areYouSureToDeleteAvatar': 'Are you sure to delete the avatar ',
		'deleteAvatarQ': 'Delete current avatar?',
		'failedToDeleteImageWithResponse': 'Failed to delete the image. Server answers: ',
		'failedToDeleteImage': 'Failed to delete the image. Try again later..',
		'topicIsNotSet': 'Topic not set.',
		'changeChannelTopic': 'Edit channel topic:',
		'changeTopicSubmit': 'Change topic',
		'youCanCopyCodesToTopic': 'You can paste message input color codes into the topic.',
		'setBy': 'Created by',
		'date': 'Date',
		'appliesTo': 'Applies to',
		'mask': 'Mask',
		'listOf': 'List of ',
		'onChannel': ' on channel ',
		'listIsEmpty': 'List is empty.',
		'ofBans': 'bans',
		'ofExcepts': 'exceptions',
		'ofInvites': 'invite exceptions',
		'allEmoticons': 'All emoticons',
		'weekdays': [ 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday' ],
		'months': [ 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec' ],
		'show': 'Show',
		'hide': 'Hide',
		'aPicture': ' image',
		'aVideo': ' video',
		'linkCanBeUnsafe': 'Link can be unsafe. Are you sure to open it?',
		'confirmJoin': 'Do you want to join the selected channel?',
		'reconnect': 'Reconnect',
		'lostNetworkConnection': 'Lost connection to the network.',
		'disconnected': 'Disconnected',
		'msgNotice': 'Message',
		'passwordNotGiven': 'Password not given!',
		'reconnectingWait': 'Reconnecting, please wait...',
		'connecting': 'Connecting',
		'pingTimeout': 'Connecting timeout',
		'nickNoLongerInUse': 'And now it\'s not: i\'ve cleared it using your password :)',
		'connectingTooLong': 'Connecting takes too long. You can wait or try again.',
		'connectingTookTooLong': 'Connecting took too long',
		'connectingWaitHtml': 'Connecting, please wait...<br />Don\'t use the "Back" or "Refresh" options now.',
		'errorLoadingData': 'Error loading from storage. Please enter the data.',
		'mustGiveNick': 'You have to provide a nickname!',
		'mustGiveChannel': 'You have to provide a channel name!',
		'badCharsInNick': 'Nickname contains invalid characters!',
		'badNickStart': 'Nickname can\'t start with a digit or minus sign!',
		'spaceInPassword': 'Password can\'t contain a space!',
		'badCharsInChan': 'Channel name contains unallowed characters',
		'information': 'Information',
		'youCanDisableAutoconnect': 'You can disable autoconnecting, for example to change the data, by clicking Settings icon in upper right corner, and disabling the "Automatic connecting" field.',
		'areYouSureToChangeTopicOf': 'Are you sure to change the topic for ',
		'itCantBeUndone': 'This can\'t be undone.',
		'clickForWholeTopic': 'Click to see the whole topic',
		'textTooLongForSingleLine': 'Entered text won\'t fit a single line. Are you sure to send it?',
		'textStartsWithSpaceAndSlash': 'Entered text starts with a "/" character, but prepended by a space. To avoid mistakes, please make a selection.',
		'sendMessage': 'Send message',
		'joinTo': 'Join ',
		'cancel': 'Cancel',
		'runCommand': 'Run command',
		'messageStartsWithHash': 'Entered text looks like an IRC channel name. Sending channel names to other channels is often regarded as spam. To avoid mistakes, please make a selection.',
		'changeSettings': 'Change settings',
		'cantPMBecauseIgnoring': 'You can\'t talk to this user because you are ignoring him/her.',
		'giveForNick': 'Give to ',
		'temporaryPrivilegesOnChan': ' current privileges on channel ',
		'selectOption': 'Select an option',
		'voicePrivilege': 'VOICE',
		'halfopPrivilege': 'HALFOP (channel half-operator)',
		'opPrivilege': 'OP (operator)',
		'sopPrivilege': 'PROTECT/SOP (administrator, kick protection)',
		'founderPrivilege': 'FOUNDER (channel owner)',
		'chanservPrivilegesOnChan': ' permanent ChanServ access on channel ',
		'youNeedServicePrivileges': '(you need to have enough permissions for services)',
		'selectAvailableOption': 'Select some option!',
		'administrationOf': 'Administration of ',
		'removeFromNick': 'Take privileges from ',
		'completelyRemoveNick': 'Completely remove user ',
		'fromChanservPrivilegesOnChan': ' from ChanServ access list on channel ',
		'dontRemove': 'No, don\'t remove',
		'yesRemove': 'Yes, remove',
		'changeChannelModesOf': 'Change modes of ',
		'character': 'Character',
		'description': 'Description',
		'inviteSomeone': 'Invite',
		'inviteUserTo': 'Invite an user to ',
		'requestsInvitationTo': ' requests access to ',
		'requestForInvitation': 'Request for invitation',
		'kickUser': 'Kick user ',
		'fromChannel': ' from channel ',
		'giveKickReason': 'You can give a KICK reason. It will be displayed to other channel members.',
		'doKick': 'Kick',
		'quitMessage': 'Quit message: ',
		'defaultQuitMessage': 'User disconnected',
		'disconnect': 'Disconnect',
		'ircQuit': 'Quit IRC',
		'hasSet': 'set ',
		'hasRemoved': 'removed ',
		'gave': 'gave ',
		'taken': 'taken ',
		'forUser': ' for',
		'alreadyConnectedAs': 'You have the client already open on another browser tab, connected as ',
		'cantOpenMultipleInstances': 'Can\'t open multiple client instances.',
		'goToTabToJoin': 'Go to that tab to join ',
		'alreadyConnected': 'Already connected!',
		'otherTabWantsToJoin': 'Another tab wants to join channel ',
		'join': 'Join',
		'confirm': 'Confirm',
		'channelList': 'channel list',
		'hideList': 'hide list',
		'insertFormatCodes': 'Insert formatting codes',
		'hideFormatting': 'Hide formatting',
		'cantSendNoConnection': 'You can\'t use a command nor send a message now because you are not connected to IRC.',
		'connectionNotAllowedHtml': '<p>Server did not allow this connection. Likely your IP address is banned.</p><p>If you are sure you did nothing wrong (please check the <a href="' + mainSettings.rulesUrl + '" target="_blank">rules</a>), try following soultions:'+
			'<ul>'+
			'<li>Disable services like VPN, Proxy, TOR. Users of such services are abusing the network so often that the network does not allow them.</li>'+
			'<li>Reset your router. Maybe your internet provider has provided you with an address that was previously abused.</li>'+
			'<li>Contact network admins with e-mail ' + mainSettings.adminMail + '</li>',
		'noAccessToNetwork': 'No access',
		'listIsEmpty': 'List is empty.',
		'listOfIgnoredUsers': 'List of ignored users',
		'channel': 'channel',
		'privateDiscussion': 'private messages',
		'addListEntry': 'Add list entry',
		'privateMessages': 'Private messages',
		'channelMessages': 'Channel messages',
		'add': 'Add',
		'operationFailed': 'Operation failed.',
		'noMaskGiven': 'Mask not given!',
		'maskCantContainSpaces': 'Mask can\'t contain spaces!',
		'neitherChannelNorQuerySelected': 'Neither channel nor query selected!',
		'cantIgnoreAllInChannels': 'You can\'t ignore all nicks!',
		'cantIgnoreNetworkService': 'You can\'t ignore a network service!',
		'ignorePMs': 'Ignore private messages',
		'ignoreChanMsgs': 'Ignore channel messages',
		'isIgnoredByWildcards': 'This user is being ignored by wildcard rules.',
		'manageIgnored': 'Manage ignored nicks',
		'ignoreUserNick': 'Ignore user ',
		'logIn': 'Log in',
		'yourPassword': 'Your password:',
		'saveThisPassword': 'Save this password',
		'newNick': 'New nick:',
		'changeNick': 'Change nick',
		'youHaveLimitedTimeToLogInHtml': 'You have <span id="nickserv_timer">limited time</span> to change your nick, the change will be then forced. Don\'t worry, you\'ll get your nickname back after entering a valid password.',
		'second': 'second',
		'second1': 's',
		'second2': 's',

		'maskBannedMask': /^Zbanowano maskę .(.*). \(dla .(.*).\)$/i,
		'youreIdentifiedMask': /^Hasło przyjęte - jesteś zidentyfikowany\(a\)\.$/i,
		'nickNotRegisteredMask': /^Nick [^ ]+ nie jest zarejestrowany\.$/i,
		'invalidPasswordMask': /^Nieprawidłowe hasło\.$/i,
		'registeredProtectedNickMask': /^Ten nick jest zarejestrowany i chroniony\.( Jeśli należy do Ciebie,)?$/i,
		'identifyMask': /^Zidentyfikuj się pisząc: /i,
		'nickBelongingToYouMask': /^jeśli nick należy do Ciebie, w przeciwnym razie zmień go\.$/i,
		'notUsedByServicesMask': /^Nick .* nie jest zajęty przez serwisy\.$/i,
		'notCurrentlyUsedMask': /^Nick .* nie jest aktualnie używany\.$/i,
		'loginPromptMask': /^wpisz .\/msg NickServ IDENTIFY .hasło..\. W przeciwnym wypadku$/i,
		'selectOtherNickMask': /^wybierz proszę inny nick.$/i,
		'accessDeniedMask': /^Odmowa dostępu\.$/i,
		'nickRemovedFromNetworkMask': /^Nick został usunięty z sieci\.$/i,
		'servicesReleasedNickMask': /^Serwisy właśnie zwolniły.*nicka.*\.$/i,
		'youHaveTimeToChangeNickMask': /^Masz (.*) na zmianę nicka, potem zostanie zmieniony siłą\.$/i,
		'ifYouDontChangeMask': /^Jeśli go nie zmienisz w ciągu (.*), zostanie zmieniony siłą\.$/i,

		'givenPasswordForNick': 'Given password for nick ',
		'isInvalidChangeNick': ' is incorrect. You can try again or change your nick.',
		'selectedNick': 'Selected nickname ',
		'isRegisteredChangeNick': ' is registered. You have to change it or provide a password.',
		'passwordForUsedNick': 'Given password to used nick ',
		'isInvalidRetryOrChangeNick': 'is invalid. You can try again to regain the nick, typing a valid password, or change this nickname.',
		'oneMinute': 'one minute',
		'n60seconds': '60 seconds',
		'n1minute': '1 minute',
		'n1minute2': '1 minute',
		'n60seconds2': '60 seconds',
		'n20seconds': '20 seconds',
		'n20seconds2': '20 seconds',
		'eachFunctionNeedsPermissions': 'Warning: each function requires suitable access levels.',
		'banUser': 'Ban user',
		'kickUser': 'Kick user',
		'nickOrMask': 'Nick or mask',
		'reason': 'Reason',
		'channelDescription': 'Channel description',
		'registerChannel': 'Register the channe;',
		'checkUserChanservStatus': 'Check ChanServ status of the user',
		'displayAccessList': 'View the access list',
		'deleteUserFromAccessList': 'Remove user from access list',
		'chanservCommandsOn': 'ChanServ commands for ',
		'workInProgress': 'Work in progress - certain options may not work and the list may not be complete!',
		'showBotList': 'Show bot list',
		'nickChosenFromBotList': 'Nick (selected from BOTLIST)',
		'assignBotToChan': 'Assign bot to channel',
		'removeBotFromChan': 'Unassign bot from channel',
		'message': 'Message',
		'sendActionToChan': 'Send message to channel (/me action)',
		'sendMessageToChan': 'Send message to channel',
		'botservCommandsOn': 'BotServ commands for ',
		'argumentRequiredForCmd': 'Argument required: ',
		'banAndKickUserFrom': 'Ban and kick user ',
		'noAutoUnban': 'Do not auto-remove the ban',
		'unban1Day': 'Auto-remove after 1 day',
		'unban1Hour': 'Auto-remove after a hour',
		'unban1Month': 'Auto-remove after a month',
		'doBan': 'Ban',
		'youNeedRegisteredNickToUseThis': 'You need a registered nickname to use this!',
		'change': 'Change',
		'nickChange': 'Nick change',
		'noNickGiven': 'Nick not given!',
		'nickCantContainSpaces': 'Nick can\'t contain spaces!',
		'password': 'Password:',
		'repeatPassword': 'Repeat password:',
		'email': 'E-mail:',
		'emailNeeded': 'The e-mail address is needed to confirm the registration, and for future password recovery.',
		'register': 'Register',
		'registrationOfNick': 'Registration of nick ',
		'passwordsNotMatching': 'Passwords do not match!',
		'mailNotGiven': 'No e-mail address entered!',
		'badEmail': 'Entered e-mail address is invalid!',
		'youHaveToWaitAnother': 'You have to wait another ',
		'secondsToRegisterNick': ' seconds, before you can register your nick.',
		'thisCommandWillRequestVhost': 'This command will send a request for new vHost to network administrators.',
		'newVhost': 'New vHost: ',
		'lettersDigitsDot': 'vHost can contain only letters and digits, and must contain at least one dot separator.',
		'proceed': 'Proceed',
		'settingOfVhost': 'VHost setting',
		'user': 'user',
		'multipleUsers': 's',
		'chanOp': 'op',
		'browserTooOldQuit': 'Browser too old!',
		'registered': 'Registered',
		'unRegistered': 'Not registered',
		'query': 'Query',
		'softwareVersion': 'Software version',
		'channelAdministration': 'Administration',
		'kickFromChannel': 'Kick from channel',
		'banUsingChanserv': 'Ban (ChanServ)',
		'givePrivileges': 'Give access',
		'takePrivileges': 'Take access',
		'loggedInAs': 'Logged in as ',
		'userIsAway': 'This user is away',
		'reason': 'reason',
		'userIsIrcop': 'This user is an IRCOperator',
		'userIsBot': 'This user is a bot',
		'nickIsRegistered': 'This nickname is registered',
		'userIsLoggedIntoAccount': 'This user is logged in as ',
		'closeQuery': 'Close query',
		'leftChannel': 'Left channel',
		'leaveChannel': 'Leave channel',
		'channelOptions': 'Channel options',
		'autoJoinThisChannel': 'Auto-join this channel',
		'enable': 'Enable',
		'disable': 'Disable',
		'clearMessageWindow': 'Clear message window',
		'refreshNickList': 'Refresh nick list',
		'administrativeActions': 'Administrative actions',
		'banList': 'Ban list (b)',
		'exceptListHint': 'Users on this list are except from bans',
		'exceptList': 'Ban exception list (e)',
		'invexListHint': 'Users on this list don\'t need an invitation if +i is set',
		'invexList': 'Invite exeption list (I)',
		'channelModes': 'Channel modes',
		'inviteToChannel': 'Invite to channel',
		'chanservCommands': 'ChanServ commands',
		'botservCommands': 'BotServ commands',
		'dontWantPrivateMessages': 'I don\'t want to receive private messages:',
		'dontWantAnyMessages': 'any (+D mode)',
		'dontWantFromUnregistered': 'from unregistered users (+R mode)',
		'dontShowAvatars': 'Don\'t display avatars (old user interface)',
		'setOwnAvatar': 'Set own avatar',
		'dontShowJoinsQuits': 'Don\'t display PART/JOIN/QUIT messages',
		'dontShowNickChanges': 'Don\'t display nick changes',
		'dontShowModes': 'Don\'t display mode changes',
		'tabListOnBottom': 'Move tab list to the bottom',
		'showHostnames': 'Display user hostnames',
		'autoReconnect': 'Automatically reconnect after disconnecting',
		'unsafeLinkWarnings': 'Display link warnings',
		'darkTheme': 'Dark theme (experimental)',
		'colorNicks': 'Color nicks in message window',
		'newMsgSound': 'Enable sound alert for new messages',
		'showEmoji': 'Replace text emoticons with emoji (for example "<g-emoji fallback-src="/styles/emoji/1f642.png">🙂</g-emoji>" for ":)")',
		'sendEmoji': 'Send above emoji to IRC',
		'monospaceFont': 'Display message window contents with a monospace font',
		'autoDisconnect': 'Automatically disconnect upon page close',
		'autoConnect': 'Auto-connecting (no nick/password prompt)',
		'backlogCount':  'Line count in previous messages storage',
		'popupWindow': 'Pop up window',
		'statusTab': 'Status tab',
		'manageIgnored': 'Manage ignored nicks',
		'allRightsReserved': 'All rights reserved',
		'statusTabName': 'Status',
		'extendChannelList': '⮙ channel list ⮙',
		'nickOptions': 'Nick options',
		'registerNick': 'Register nick',
		'privateMessagesBlocking': 'Private messages blocking',
		'requestAVhost': 'Request a vHost',
		'showChannelsWithAccess': 'Show channels you have access to',
		'showAutojoinChannels': 'Show your autojoin channels',
		'insertFormatCodes': '⮛ Insert formatting codes ⮛',
		'insertColorCode': 'Insert color code',
		'insertSpecialCode': 'Insert special code',
		'turnOffColor': 'Turn off color',
		'boldText': 'Bold',
		'reverseColors': 'Reverse',
		'italicText': 'Italic',
		'underscoreText': 'Underline',
		'clearFormats': 'Clear formatting',
		'emoticons': 'Emoticons',
		'showAllAvailable': 'Show all available',
		'thisCanTakeTime': '(this may take some time)',
		'engineeringSymbols': 'Engineering symbols',
		'version': 'Version',
		'statusWindow': 'Status window',
		'noticeDisplay': 'NOTICE display method',
		'connectingForTooLong': 'Connecting is taking too long, the server is not working or your browser is not functioning properly.<br>Try again later or try ',
		'channel': 'Channel',
		'passwordIfRegistered': 'Password (if registered)',
		'savePassword': 'Save password',
		'saveAllAndDontShowAgain': 'Save all data and do not display this anymore',
		'connectToIRC': 'Connect to IRC',
		'logon': 'Logging in',
		'userClosedPage': 'User has closed the page',
		'youreStillConnected': 'You are still connected to IRC. Click "Stay on page" and then "Disconnect" in the window below to disconnect before leaving.',
		'cookiesDisabledHtml': 'Your browser has cookies disabled. Some functionality may not work properly.<br><input type="button" onclick="conn.dispConnectDialog();" value="Continue">',
		'websocketDisabledHtml': 'Your browser does not support WebSocket. Can\'t run the application.<br>Try ',
		'close': 'Close',
		'none': 'none',
		'disconnectOnRequest': 'Disconnected from IRC on demand.',
		'youHaveToGiveNewNick': 'you have to provide a nick to change to.',
		'youHaveToGiveQueryNick': 'you have to provide a nick to get info about.',
		'youHaveToGivePMNick': 'you have to provide a nick to start talking with.',
		'youHaveToGiveChanFirstArg': 'you have to provide a channel name as first argument.',
		'youHaveToGiveChannelToJoin': 'you have to provide a channel name to join.',
		'youHaveToGiveInviteNickChannel': 'you have to provide user nickname and a channel name to invite the user to.',
		'youHaveToGiveKnockChan': 'you have to provide a channel name to knock to.',
		'youHaveToGiveMsgText': 'you have to provide some text to send.',
		'youHaveToGiveMsgNickText': 'you have to provide the destination nick and the some text to send.',
		'youHaveToGivePartChan': 'you have to provide a channel name to part as the first argument.',
		'youHaveToGiveKickChan': 'you have to provide a channel to kick this user from as the first argument.',
		'youHaveToGiveKickNick': 'you have to provide a nick to kick as the first argument.',
		'youHaveToBeOnChan': 'you have to be on a channel to use this command.',
		'youHaveToGiveChannelToTakeGivePerms': 'you have to provide a channel name to give/take permissions on.',
		'youHaveToGiveChannelAndNickToTakeGivePerms': 'you have to provide a channel name and a nickname to give or take permissions from.',
		'youHaveToGiveChanOrNick': 'you have to provide a nick or channel as the first argument.',
		'privateMsgBlocking': 'Private message blocking',
		'settings': 'Settings',
		'showUserHostTitle': 'Shows user@host information in channel parts and joins',
		'linkInfoTitle': 'This does not apply to already displayed links',
		'noticeDisplayTitle': 'If the query window is already open, all notices will go there in any case',
		'avatar': 'Avatar',
		'changeSizeTitle': 'Change text size',
		'gatewayInfoTitle': 'Web client information',
		'disconnectWithIrc': 'Disconnect from IRC',
		'tabTitle': 'Auto-complete nick or command [Tab]',
		'emoticonsSymbolsTitle': 'Emoticons and symbols',
		'colorsFormattingTitle': 'Colours and formatting',
		'enterTitle': 'Send [Enter]',
		'textFormattingTitle': 'Text formatting',
		'symbolsTitle': 'Symbols',
		'selectTextSizeTitle': 'Select text size',
		'ignoreThis': 'Ignore',
		'topicOfChannel': 'Topic of ',
		'mode': 'mode',
		'enterUrl': 'Enter URL address:',
		'selectAnImage': 'Select an image:',
		'yes': 'Yes',
		'no': 'No',
		'messageNotDelivered': 'This message was not delivered',
		'historyEntry': 'Message history entry',
		'getMoreHistory': 'Get more history…'
	}
};

function setLanguage(slang){
	window.language = lang[slang];
	// fill static HTML with translations
	$('.language-privateMsgBlockingTitle').attr('title', language.privateMsgBlocking);
	$('.language-settingsTitle').attr('title', language.settings);
	$('.language-showUserHostTitle').attr('title', language.showUserHostTitle);
	$('.language-linkInfoTitle').attr('title', language.linkInfoTitle);
	$('.language-noticeDisplayTitle').attr('title', language.noticeDisplayTitle);
	$('.language-avatarTitle').attr('title', language.avatar);
	$('.language-informationsTitle').attr('title', language.informations);
	$('.language-changeSizeTitle').attr('title', language.changeSizeTitle);
	$('.language-gatewayInfoTitle').attr('title', language.gatewayInfoTitle);
	$('.language-disconnectWithIrcTitle').attr('title', language.disconnectWithIrc);
	$('.language-tabTitle').attr('title', language.tabTitle);
	$('.language-emoticonsSymbolsTitle').attr('title', language.emoticonsSymbolsTitle);
	$('.language-colorsFormattingTitle').attr('title', language.colorsFormattingTitle);
	$('.language-enterTitle').attr('title', language.enterTitle);
	$('.language-textFormattingTitle').attr('title', language.textFormattingTitle);
	$('.language-symbolsTitle').attr('title', language.symbolsTitle);
	$('.language-selectTextSizeTitle').attr('title', language.selectTextSizeTitle);
	$('.language-noticeDisplay').html(language.noticeDisplay);
	$('.language-version').html(language.version);
	$('.language-statusWindow').html(language.statusWindow);
	$('.language-underscoreText').html(language.underscoreText);
	$('.language-clearFormats').html(language.clearFormats);
	$('.language-emoticons').html(language.emoticons);
	$('.language-showAllAvailable').html(language.showAllAvailable);
	$('.language-thisCanTakeTime').html(language.thisCanTakeTime);
	$('.language-engineeringSymbols').html(language.engineeringSymbols);
	$('.language-dontWantPrivateMessages').html(language.dontWantPrivateMessages);
	$('.language-dontWantAnyMessages').html(language.dontWantAnyMessages);
	$('.language-dontWantFromUnregistered').html(language.dontWantFromUnregistered);
	$('.language-dontShowAvatars').html(language.dontShowAvatars);
	$('.language-setOwnAvatar').html(language.setOwnAvatar);
	$('.language-dontShowJoinsQuits').html(language.dontShowJoinsQuits);
	$('.language-dontShowNickChanges').html(language.dontShowNickChanges);
	$('.language-dontShowModes').html(language.dontShowModes);
	$('.language-tabListOnBottom').html(language.tabListOnBottom);
	$('.language-showHostnames').html(language.showHostnames);
	$('.language-autoReconnect').html(language.autoReconnect);
	$('.language-unsafeLinkWarnings').html(language.unsafeLinkWarnings);
	$('.language-darkTheme').html(language.darkTheme);
	$('.language-colorNicks').html(language.colorNicks);
	$('.language-newMsgSound').html(language.newMsgSound);
	$('.language-showEmoji').html(language.showEmoji);
	$('.language-sendEmoji').html(language.sendEmoji);
	$('.language-monospaceFont').html(language.monospaceFont);
	$('.language-autoDisconnect').html(language.autoDisconnect);
	$('.language-autoConnect').html(language.autoConnect);
	$('.language-backlogCount').html(language.backlogCount);
	$('.language-popupWindow').html(language.popupWindow);
	$('.language-query').html(language.query);
	$('.language-statusTab').html(language.statusTab);
	$('.language-manageIgnored').html(language.manageIgnored);
	$('.language-allRightsReserved').html(language.allRightsReserved);
	$('.language-statusTabName').html(language.statusTabName);
	$('.language-loadingWait').html(language.loadingWait);
	$('.language-extendChannelList').html(language.extendChannelList);
	$('.language-nickOptions').html(language.nickOptions);
	$('.language-registerNick').html(language.registerNick);
	$('.language-changeNick').html(language.changeNick);
	$('.language-privateMessagesBlocking').html(language.privateMessagesBlocking);
	$('.language-requestAVhost').html(language.requestAVhost);
	$('.language-showChannelsWithAccess').html(language.showChannelsWithAccess);
	$('.language-showAutojoinChannels').html(language.showAutojoinChannels);
	$('.language-insertFormatCodes').html(language.insertFormatCodes);
	$('.language-insertColorCode').html(language.insertColorCode);
	$('.language-insertSpecialCode').html(language.insertSpecialCode);
	$('.language-turnOffColor').html(language.turnOffColor);
	$('.language-boldText').html(language.boldText);
	$('.language-reverseColors').html(language.reverseColors);
	$('.language-italicText').html(language.italicText);
};

function setDefaultLanguage(){
	try {
		if(localStorage.getItem('setLanguage') == null){
			$('#setLanguage').val(mainSettings.language);
		} else {
			$('#setLanguage').val(localStorage.getItem('setLanguage'));
		}
	} catch(e){
		console.error('Error setting language!');
		$('#setLanguage').val(mainSettings.language);
	}
	conn.setLanguage();
}

