var mainSettings = { // TODO move this to a more relevant place
	'networkName': 'PIRC.pl',
	'avatarUploadUrl': 'https://users.pirc.pl/image-upload/image-upload.php',
	'avatarDeleteUrl': 'https://users.pirc.pl/image-upload/image-delete.php',
	'defaultName': 'Użytkownik bramki PIRC.pl',
	
};
	

var lang = {
	'pl': {
		'messagePatterns': {
			'nickChange': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ <span class="modeinfo">%s</span> zmienił nick na <span class="modeinfo">%s</span></span></div><!--newline-->',
			'nickInUse': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick">✯ <span class="modeinfo">%s</span>: Nick jest już używany przez kogoś innego.</span></div><!--newline-->',
			'badNick': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick">⮿ <span class="modeinfo">%s</span>: Nick nie jest dostępny.</span></div><!--newline-->',
			'nickChangeOwn': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ Jesteś teraz znany jako <span class="modeinfo">%s</span></span></div><!--newline-->',
			'joinOwn': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="join">🢡 Dołączyłeś do kanału <span class="modeinfo">%s</span>.</span></div><!--newline-->',
			'join': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="join">🢡 <b>%s</b> <i class="userhost">[%s@%s]</i> dołączył do <span class="modeinfo">%s</span>.</span></div><!--newline-->',
			'part': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="part">🢠 <b>%s</b> <i class="userhost">[%s@%s]</i> opuścił <span class="modeinfo">%s</span> [%s]</span></div><!--newline-->',
			'quit': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="part">🢠 <b>%s</b> <i class="userhost">[%s@%s]</i> opuścił IRC [%s]</span></div><!--newline-->',
			'partOwn': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="part">🢠 Opuściłeś kanał <span class="modeinfo">%s</span>. <a href="#" onclick="gateway.send(\'JOIN %s\')">Dołącz ponownie</a></span></div><!--newline-->',
			'channelMsg': '<div class="messageDiv %s" data-msgid="%s"><div class="messageMeta">%s</div><div class="messageHeader"><span class="time">%s &nbsp;</span><span class="nick">&lt;<span %s>%s</span>&gt;%s</span></div><span class="msgText">%s</span></div><!--newline-->',
			'yourMsg': '<div class="messageDiv %s" data-msgid="%s"><div class="messageMeta">%s</div><div class="messageHeader"><span class="time">%s &nbsp;</span><span class="yournick">&lt;<span %s>%s</span>&gt;%s</span></div><span class="msgText">%s</span></div><!--newline-->',
			'channelMsgHilight': '<div class="messageDiv %s" data-msgid="%s"><div class="messageMeta">%s</div><div class="messageHeader"><span class="time">%s &nbsp;</span><span class="hilight"><span class="nick">&lt;%s&gt;%s</span></span></div><span class="msgText">%s</span></div><!--newline-->',
			'channelAction': '<div class="messageDiv" data-msgid="%s"><span class="time">%s</span> &nbsp; ❇ <span class="nick">%s</span> %s</div><!--newline-->',
			'yourAction': '<div class="messageDiv" data-msgid="%s"><span class="time">%s</span> &nbsp; ❇ <span class="yournick">%s</span> %s</div><!--newline-->',
			'channelActionHilight': '<div class="messageDiv" data-msgid="%s"><span class="time">%s</span> &nbsp; ❇ <span class="hilight"><span class="nick">%s</span> %s</span></div><!--newline-->',
			'changeTopic': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ <span class="modeinfo">%s</span> zmienił temat na: %s</span></div><!--newline-->',
			'deleteTopic': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ <span class="modeinfo">%s</span> usunął temat <span class="modeinfo">%s</span></span></div><!--newline-->',
			'topic': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ Temat kanału <span class="modeinfo">%s</span>: %s</span></div><!--newline-->',
			'topicNotSet': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ Temat <span class="modeinfo">%s</span> nie jest ustawiony</span></div><!--newline-->',
			'topicTime': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ Temat ustawiony przez <span class="modeinfo">%s</span> [%s]</span></div><!--newline-->',
			'kick': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick">✀ <span class="modeinfo">%s</span> wyrzucił <span class="modeinfo">%s</span> z <span class="modeinfo">%s</span> [Powód: %s]</span></div><!--newline-->',
			'kickOwn': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick">✀ <span class="modeinfo">%s</span> wyrzucił cię z <span class="modeinfo">%s</span> [Powód: %s]</span></div><!--newline-->',
			'modeChange': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">🔧 <span class="modeinfo">%s</span> %s na kanale <span class="modeinfo">%s</span></span></div><!--newline-->',
			'mode': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">🔧 Ustawienia kanału <span class="modeinfo">%s</span>: %s</span></div><!--newline-->',
			'creationTime': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ Kanał stworzony: %s</span></div><!--newline-->',
			'startedQuery': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="join">🢡 Rozpoczęto rozmowę z <span class="modeinfo">%s</span>. <a onclick="ignore.askIgnore(\'%s\');">Ignoruj tego użytkownika</a> / <a onclick="disp.showQueryUmodes()">Blokowanie wiadomości prywatnych</a></span></div><!--newline-->',
			'queryBacklog': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="join">✯ Zapis poprzedniej rozmowy z <span class="modeinfo">%s</span>:</span></div><!--newline-->',
			'channelBacklog': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ Zapis poprzedniej wizyty na <span class="modeinfo">%s</span>:</span></div><!--newline-->',
			'channelBacklogEnd': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ Koniec zapisu.</span></div><!--newline-->',
			'noSuchCommand': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">⮿ <span class="modeinfo">%s</span>: nieznana komenda.</span></div><!--newline-->',
			'noSuchNick': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">⮿ <span class="modeinfo">%s</span>: nie ma takiego nicku ani kanału</span></div><!--newline-->',
			'noSuchNickHistory': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">⮿ <span class="modeinfo">%s</span>: brak historii wizyt nicka</span></div><!--newline-->',
			'noSuchChannel': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">⮿ <span class="modeinfo">%s</span>: nie ma takiego kanału</span></div><!--newline-->',
			'notOnChannel': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">⮿ <span class="modeinfo">%s</span>: nie jesteś na tym kanale</span></div><!--newline-->',
			'alreadyOnChannel': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">⮿ %s: <span class="modeinfo">%s</span> jest już na tym kanale</span></div><!--newline-->',
			'youQuit': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="part">✯ Wyszedłeś z IRC</span></div><!--newline-->',
			'notConnected': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">⮿ Nie jesteś połączony z IRC!</span></div><!--newline-->',
			'notEnoughParameters': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">⮿ <span class="modeinfo">%s</span>: Za mało argumentów.</span></div><!--newline-->',
			'cannotSendToChan': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick">⮿ Nie można wysłać na <span class="modeinfo">%s</span>: %s. Wiadomość nie została dostarczona.</span></div><!--newline-->',
			'cannotSendToUser': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick">⮿ Nie można pisać do <span class="modeinfo">%s</span>: %s. Wiadomość nie została dostarczona.</span></div><!--newline-->',
			'cannotJoin': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick">⮿ Nie można dołączyć do kanału <span class="modeinfo">%s</span>: %s</span></div><!--newline-->',
			'noPerms': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick">⮿ Brak uprawnień.</span></div><!--newline-->',
			'notice': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="notice-nick"><b>-%s-</b></span><span class="userhost">(<span class="notice-nick">%s</span>@<span class="notice-nick">%s</span>)</span> <span class="notice">%s</span></div><!--newline-->',
			'serverNotice': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="notice-nick">Wiadomość od serwera <b>%s</b>:</span> <span class="notice">%s</span></div><!--newline-->',
			'yourNotice': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="notice"><b>-NOTICE/%s-</b> %s</span></div><!--newline-->',
			'notEnoughParams': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">⮿ <span class="modeinfo">%s</span>: za mało argumentów: %s</span></div><!--newline-->',
			'motd': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="motd">✯ %s</span></div><!--newline-->',
			'SaslAuthenticate': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="sinfo">🔧 %s</span></div><!--newline-->',
			'ctcpRequest': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ <span class="modeinfo">%s</span> wysyła CTCP REQUEST: %s</span></div><!--newline-->',
			'ctcpReply': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="notice">✯ <b>CTCP REPLY od %s:</b> %s</span></div><!--newline-->',
			'chanListElement': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="notice">✯ <b><a href="#" onClick="gateway.send(\'JOIN %s\')">%s</a></b> (%s) - %s </span> </div><!--newline-->',
			'chanListElementHidden': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="notice">✯ <b>(kanał ukryty)</b> (%s) - (temat ukryty) </span> </div><!--newline-->',
			'error': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode"> ⮿ Rozłączono z serwerem: %s</span></div><!--newline-->',
			'existingConnection': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ Połączenie już istnieje, dołączam się do niego.</span></div><!--newline-->',
			'away': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">🍵 <span class="modeinfo">%s</span> otrzymał twoją wiadomość, ale jest teraz nieobecny: %s</span></div><!--newline-->',
			'yourAwayEnabled': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">🍵 Jesteś teraz oznaczony jako nieobecny</span></div><!--newline-->',
			'yourAwayDisabled': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">🍵 Nie jesteś już oznaczony jako nieobecny</span></div><!--newline-->',
			'yourInvite': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ Zaprosiłeś użytkownika <span class="modeinfo">%s</span> na kanał <span class="modeinfo">%s</span></span></div><!--newline-->',
			'knocked': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ Poprosiłeś o dostęp ("zapukałeś") na <span class="modeinfo">%s</span>, czekaj na zaproszenie od operatora. Pamiętaj, że w danej chwili żaden operator może nie być przy komputerze. W takiej sytuacji zaczekaj kilkadziesiąt minut i spróbuj jeszcze raz.</span></div><!--newline-->',
			'listShown': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ Lista kanałów będzie wyświetlona w zakładce statusu.</span></div><!--newline-->',
			'channelIgnoreAdded': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ Dodano <b>%s</b> do ignorowanych na kanałach.</span></div><!--newline-->',
			'channelIgnoreRemoved': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ Usunięto <b>%s</b> z ignorowanych na kanałach.</span></div><!--newline-->',
			'queryIgnoreAdded': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ Dodano <b>%s</b> do ignorowanych prywatnie.</span></div><!--newline-->',
			'queryIgnoreRemoved': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ Usunięto <b>%s</b> z ignorowanych prywatnie.</span></div><!--newline-->',
			'ignoreListStart': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ Lista ignorowanych:</span></div><!--newline-->',
			'ignoreListEnd': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ Koniec listy.</span></div><!--newline-->',
			'ignoreListEmpty': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ Lista ignorowanych jest pusta.</span></div><!--newline-->',
			'ignoreListItem': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="mode">✯ Typ: <b>%s</b>, maska: <b>%s</b></span></div><!--newline-->',
			'netsplit': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="part">🢠 <span class="netsplit">Netsplit</span>, wychodzą: %s</span></div><!--newline-->',
			'netjoin': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="join">🢡 Po <span class="netjoin">netsplicie</span> wchodzą: %s</span></div><!--newline-->',
			'displayedHost': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="sinfo">🔧 Twój host jest teraz widoczny jako %s</span></div><!--newline-->',
			'invalidMode': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick">⮿ Nieprawidłowy tryb "%s"</span></div><!--newline-->',
			'unimplemented': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="sinfo">✯ %s</span></div><!--newline-->',
			'unimplementedError': '<div class="messageDiv"><span class="time">%s</span> &nbsp; <span class="kick">⮿ %s</span></div><!--newline-->'
		},
		'SASLLogin': 'SASL: logowanie do konta ',
		'SASLLoginAttempt': 'Próba logowania za pomocą SASL...',
		'recoverErrorHtml': '<h2>Błąd ogólny</h2><p>Inna sesja rozłączyła Cię używając polecenia RECOVER. Może masz otwartą więcej niż jedną bramkę?</p>',
		'error': 'Błąd',
		'serverClosedConnection': 'Serwer przerwał połączenie',
		'informations': 'Informacje',
		'inviting': 'zaprasza Cię na kanał',
		'enter': 'Wejdź',
		'ignore': 'Zignoruj',
		'invitation': 'Zaproszenie',
		'userInformation': 'Informacje o użytkowniku ',
		'userSoftware': 'Oprogramowanie użytkownika ',
		'networkServiceMessage': 'Komunikat od usługi sieciowej',
		'privateNoticeFrom': 'Komunikat prywatny od ',
		'privateNoticeFromServer': 'Komunikat prywatny od serwera ',
		'realNickname': 'Prawdziwy nick na IRC',
		'notLoggedIn': 'Niezalogowany',
		'loggedIn': 'Zalogowany',
		'loggedInAs': 'Zalogowany jako ',
		'warning': 'Ostrzeżenie',
		'yourCurrentNickIs': 'Twój bieżący nick to ',
		'notPresent': 'Nieobecny',
		'isNotPresent': ' jest nieobecny(a): ',
		'nickRegistered': 'Ten nick jest zarejestrowany',
		'fullMask': 'Pełna maska',
		'realname': 'Realname',
		'userInformation': 'Informacje o użytkowniku ',
		'server': 'Serwer',
		'seen': 'Widziano',
		'ircop': 'OPERATOR SIECI',
		'networkService': 'Usługa sieciowa',
		'previousVisitsBy': 'Poprzednie wizyty ',
		'signedOn': 'Połączył się',
		'idle': 'Nieaktywny',
		'hoursShort': 'h',
		'minutesShort': 'min',
		'secondsShort': 'sek',
		'joinChannel': 'Dołącz do kanału',
		'channels': 'Kanały',
		'isConnectingFrom': 'Łączy się z: ',
		'noTopic': 'brak tematu',
		'fullList': 'Pełna lista',
		'refresh': 'Odśwież',
		'largestChannels': 'Największe kanały',
		'accountName': 'Nazwa konta',
		'isBotHtml': 'Ten użytkownik to <b>bot</b>',
		'nickListFor': 'Lista nicków dla ',
		'noSuchNickChannel': 'Nie można wykonać żądanej akcji. Nie ma takiego nicku ani kanału',
		'noSuchObject': 'Nie można wykonać żądanej akcji. Nie ma takiego obiektu',
		'noSuchChannel': 'Nie można wykonać żądanej akcji. Nie ma takiego kanału',
		'needVoice': 'Potrzebujesz prawa głosu, aby teraz pisać na tym kanale',
		'youreBanned': 'Jesteś zbanowany',
		'colorsForbidden': 'Wiadomości zawierające kolory są zabronione na tym kanale',
		'noExternalMsgs': 'Musisz być na tym kanale, aby móc pisać',
		'registeredNickRequired': 'Musisz mieć zarejestrowanego nicka, aby teraz pisać na tym kanale',
		'serverMessageIs': 'Komunikat od serwera: ',
		'cantSendMessageTo': 'Nie można wysłać wiadomości do ',
		'recentVisitsForNickNotFound': 'Nie znaleziono poprzednich wizyt nicka: ',
		'isCurrentlyNotAvailable': ' jest niedostępny. Spróbuj poczekać kilka minut.',
		'nickname': 'Nick',
		'yourCurrentNickIs': 'Twój bieżący nick to ',
		'isAlreadyUsedBySomeone': ' jest już używany przez kogoś innego.',
		'youreNotOnChannel': ' nie jesteś na tym kanale.',
		'isAlreadyOnChannel': ' jest już na tym kanale.',
		'cantChangeNickMessageHtml': 'Nie można zmienić nicka.<br>Komunikat od serwera: ',
		'invalidMode': 'Nieprawidłowy tryb',
		'cantJoin': 'Nie można dołączyć do kanału',
		'inviteRequired': 'Musisz dostać zaproszenie aby wejść na ten kanał.',
		'inviteRequiredShort': 'Kanał wymaga zaproszenia',
		'askOpersForEntry': 'Poproś operatorów o możliwość wejścia',
		'entryRequest': 'Proszę o możliwość wejścia na kanał',
		'needValidPassword': 'Musisz podać poprawne hasło',
		'passwordRequired': 'Wymagane hasło',
		'registerYourNickToJoin': 'Kanał wymaga, aby Twój nick był zarejestrowany. Zastosuj się do instrukcji otrzymanych od NickServ.',
		'registeredNickRequiredForChan': 'Kanał wymaga zarejestrowanego nicka',
		'cantKnock': 'Nie można zapukać do kanału.',
		'noAccess': 'brak uprawnień',
		'notEnoughPrivileges': 'Nie masz wystarczających uprawnień aby wykonać żądaną akcję.',
		'cantSendPMTo': 'Nie można wysłać prywatnej wiadomości do ',
		'cantSendPM': 'Nie można wysłać prywatnej wiadomości.',
		'yourNickMustBeRegistered': 'Twój nick musi być zarejestrowany',
		'userAcceptsPMsOnlyFromRegistered': 'Użytkownik akceptuje prywatne wiadomości tylko od zarejestrowanych nicków.',
		'SSLRequired': 'Kanał wymaga połączenia z włączonym SSL.',
		'noPermsForAction': 'Nie masz wystarczających uprawnień aby wykonać żądaną akcję',
		'hasSecureConnection': 'Używa bezpiecznego połączenia',
		'weAreloggedInAs': 'Zalogowano jako ',
		'SASLLoginSuccess': 'SASL: logowanie udane.',
		'SASLLoginFail': 'SASL: logowanie nieudane!',
		'suppliedNickPassword': 'Podane hasło do nicka ',
		'passwordInvalidTryAgain': ' jest błędne. Możesz spróbować ponownie lub zmienić nicka.',
		'SASLNotLoggedIn': 'SASL: nie zalogowano.',
		'gatewayVersionIs': 'Bramka WWW PIRC.PL, wersja ',
		'versionWithAddons': ', z dodatkami: ',
		'runningOn': 'na',
		'unknown': 'Nieznany',
		'chStatusInfo': [ 'Niezarejestrowany', 'Prawo głosu', 'Pół-operator', 'Operator', 'Admin', 'Właściciel', 'Zarejestrowany' ],
		'modes': {
			'changeableSingle': [
				['m', 'Kanał moderowany'],
				['i', 'Tylko na zaproszenie'],
				['s', 'Kanał ukryty'],
				['R', 'Tylko dla zarejestrowanych nicków'],
				['N', 'Zakaz zmiany nicków'],
				['Q', 'Zakaz kopania'],
				['M', 'Do mówienia wymagany zarejestrowany nick lub co najmniej +v'],
				['t', 'Tylko operator może zmieniać temat'],
				['n', 'Nie można wysyłać wiadomości nie będąc na kanale'],
				['D', 'Użytkownicy będą widoczni na liście tylko wtedy, gdy coś napiszą']
			],
			'changeableArg': [
				['k', 'Hasło do kanału'],
				['l', 'Maksymalna ilość użytkowników']
			],
			'chModeInfo': {
				'q': 'status właściciela',
				'a': 'status admina',
				'o': 'status operatora',
				'h': 'status pół-operatora',
				'v': 'prawo głosu',
				'k': 'hasło:',
				'b': 'bana na',
				'e': 'wyjątek bana na',
				'I': 'stałe zaproszenie na',
				'f': 'zabezpieczenie przed floodem:',
				'p': 'tryb prywatny',
				's': 'tryb ukryty',
				'm': ['moderację', 'kanał moderowany'],
				'n': 'brak wiadomości z zewnątrz',
				't': ['ochronę tematu', 'chroniony temat'],
				'i': 'wejście tylko na zaproszenie',
				'r': ['rejestrację', 'zarejestrowany'],
				'R': 'wejście tylko dla zarejestrowanych',
				'c': ['blokadę kolorów', 'blokada kolorów'],
				'O': 'tryb O',
				'Q': ['blokadę kopania', 'zablokowane kopanie'],
				'K': ['blokadę pukania', 'zablokowane pukanie'],
				'V': ['blokadę zaproszeń', 'zablokowane zaproszenia'],
				'C': ['blokadę CTCP', 'zablokowane CTCP'],
				'z': 'wejście tylko dla połączeń szyfrowanych',
				'N': ['blokadę zmian nicków', 'zablokowana zmiana nicków'],
				'S': 'usuwanie kolorów',
				'M': ['moderację niezarejestrowanych', 'niezarejestrowani są moderowani'],
				'T': ['blokadę NOTICE', 'zablokowane NOTICE'],
				'G': 'tryb G',
				'D': 'tryb D: użytkownicy będą widoczni na liście tylko wtedy, gdy coś napiszą',
				'd': 'tryb d',
				'L-add': 'przekierowanie na kanał',
				'L-remove': 'przekierowanie na inny kanał',
				'l-add': 'limit użytkowników na',
				'l-remove': 'limit użytkowników',
				'H-add': 'pamięć historii kanału',
				'H-remove': 'pamięć historii kanału'
			},
			'chStatusNames': {
				'q': 'owner',
				'a': 'admin',
				'o': 'op',
				'h': 'halfop',
				'v': 'voice'
			},
			'newMessage': 'Nowa wiadomość',
			'loading': 'Ładowanie',
			'loadingWait': 'Poczekaj chwilę, trwa ładowanie...',
			'outdatedBrowser': 'Przestarzała przeglądarka',
			'outdatedBrowserInfo': 'Twoja przeglądarka jest przestarzała i nie jest obsługiwana. Należy zaktualizować przeglądarkę Internet Explorer do wersji 9 lub wyższej albo użyć innej przeglądarki (Firefox, Opera, Chrome, Safari) w którejś z nowszych wersji.<br />Jeżeli posiadasz przeglądarkę Internet Explorer w wersji 9 lub wyższej i widzisz ten komunikat wyłącz tzw "widok zgodności" dla tej strony.',
			'noAvatarSet': 'Nie ustawiono awatara',
			'remove': 'Skasuj',
			'check': 'Sprawdź',
			'applySetting': 'Zatwierdź',
			'avatarFileInfo': 'URL powinien prowadzić bezpośrednio do obrazka (png, gif, jpeg).',
			'browserTooOldForAvatars': 'Twoja przeglądarka jest zbyt stara, aby obsłużyć wygodniejsze ustawianie awatarów.',
			'registerNickForAvatars': 'Zarejestruj nicka i potwierdź adres e-mail, aby uzyskać dostęp do wygodniejszego ustawiania awatarów.',
			'currentAvatar': 'Bieżący awatar',
			'youAcceptToStoreTheData': 'Klikając "Zatwierdź" wyrażasz zgodę na przechowywanie podanych danych na serwerach ',
			'addressMustStartWithHttps': 'Adres musi zaczynać się od "https://"!',
			'preview': 'Podgląd',
			'acceptPreview': 'Podgląd powyżej. Jeśli widać obrazek, możesz go zatwierdzić.',
			'noFileSelected': 'Nie wybrano pliku!',
			'processing': 'Trwa przetwarzanie, czekaj...',
			'failedToSendImageWithResponse': 'Błąd wysyłania obrazka. Odpowiedź serwera: ',
			'failedToSendImage': 'Nie udało się przesłać obrazka. Upewnij się, że plik nie jest zbyt duży, i spróbuj ponownie później.',
			'areYouSureToDeleteAvatar': 'Czy usunąć awatar ',
			'deleteAvatarQ': 'Czy usunąć bieżący awatar?',
			'failedToDeleteImageWithResponse': 'Błąd kasowania obrazka. Odpowiedź serwera: ',
			'failedToDeleteImage': 'Nie udało się skasować awatara. Spróbuj ponownie później.',
			'topicIsNotSet': 'Nie ustawiono tematu.',
			'changeChannelTopic': 'Zmodyfikuj temat kanału:',
			'changeTopicSubmit': 'Zmień temat',
			'youCanCopyCodesToTopic': 'Do tematu możesz skopiować kody formatowania wstawione w pole wiadomości.',
			'setBy': 'Założony przez',
			'date': 'Data',
			'appliesTo': 'Dotyczy',
			'mask': 'Maska',
			'listOf': 'Lista ',
			'onChannel': ' na kanale ',
			'listIsEmpty': 'Lista jest pusta.',
			'ofBans': 'banów',
			'ofExcepts': 'wyjątków',
			'ofInvites': 'zaproszeń',
			'allEmoticons': 'Wszystkie emotikony',
			'weekdays': [ 'Niedziela', 'Poniedziałek', 'Wtorek', 'Środa', 'Czwartek', 'Piątek', 'Sobota' ],
			'months': [ 'sty', 'lut', 'mar', 'kwi', 'maj', 'cze', 'lip', 'sie', 'wrz', 'paź', 'lis', 'gru' ],
			'show': 'Pokaż',
			'hide': 'Ukryj',
			'aPicture': ' obrazek',
			'aVideo': ' film',
			'linkCanBeUnsafe': 'Link może być niebezpieczny, czy na pewno chcesz go otworzyć?',
			'confirmJoin': 'Czy chcesz dołączyć do wybranego kanału?',
			'reconnect': 'Połącz ponownie',
			'lostNetworkConnection': 'Utracono połączenie z siecią.',
			'disconnected': 'Rozłączono',
			'msgNotice': 'Komunikat',
			'passwordNotGiven': 'Nie podałeś hasła!',
			'reconnectingWait': 'Ponowne łączenie, czekaj...',
			'connecting': 'Łączenie',
			'pingTimeout': 'Przekroczony czas odpowiedzi serwera',
			'nickNoLongerInUse': 'I już nie jest: usunąłem go używając Twojego hasła :)',
			'connectingTooLong': 'Łączenie trwa zbyt długo. Możesz poczekać lub spróbować jeszcze raz.',
			'connectingTookTooLong': 'Zbyt długi czas łączenia',
			'connectingWaitHtml': 'Poczekaj, trwa łączenie...<br />Nie używaj teraz przycisku "Wstecz" ani "Odśwież".',
			'errorLoadingData': 'Błąd wczytywania danych z ciasteczek. Wpisz dane.',
			'mustGiveNick': 'Musisz podać nicka!',
			'mustGiveChannel': 'Musisz podać kanał!',
			'badCharsInNick': 'Nick zawiera niedozwolone znaki!',
			'badNickStart': 'Nick nie może zaczynać się od cyfry ani minusa!',
			'spaceInPassword': 'Hasło nie powinno zawierać spacji!',
			'badCharsInChan': 'Kanał zawiera niedozwolone znaki!',
			'information': 'Informacja',
			'youCanDisableAutoconnect': 'Możesz wyłączyć automatyczne łączenie, na przykład w celu zmiany danych, klikając na ikonę ustawień w prawym górnym rogu, i odznaczając pole "Automatyczne łączenie".',
			'areYouSureToChangeTopicOf': 'Czy zmienić temat dla ',
			'intCantBeUndone': 'Nie można tego cofnąć.',
			'clickForWholeTopic': 'Kliknij aby zobaczyć cały temat',
			'textTooLongForSingleLine': 'Wpisany tekst nie zmieści się w jednej linijce. Czy na pewno chcesz go wysłać?',
			'textStartsWithSpaceAndSlash': 'Wpisany tekst zaczyna się od znaku "/", ale poprzedzonego spacją. Aby uniknąć pomyłki, wybierz, co chcesz zrobić.',
			'sendMessage': 'Wyślij wiadomość',
			'joinTo': 'Dołącz do ',
			'cancel': 'Anuluj',
			'runCommand': 'Wykonaj polecenie',
			'messageStartsWithHash': 'Wpisana wiadomość wygląda jak nazwa kanału IRC. Podawanie nazw kanałów na innych kanałach jest często uznawane jako spam. Aby uniknąć pomyłki, wybierz, co chcesz zrobić.',
			'changeSettings': 'Zmień ustawienia',
			'cantPMBecauseIgnoring': 'Nie możesz rozmawiać prywatnie z tym użytkownikiem, ponieważ jest na Twojej liście ignorowanych.',
			
		}
	}
};

